/**
 * Part 12 membership: cross-language parity (replays the `membership`
 * sections of docs/fixtures/coordination_fixtures.json, generated by
 * libs/trading-core/scripts/gen_part11_fixtures.py from the Python module)
 * plus behaviour of the Node-side registry against a fake Redis that - like
 * the Python double - only speaks the pinned script texts.
 *
 * If a vector fails, do NOT regenerate the fixture to make it pass: fix the
 * side that drifted, regenerate from Python, and let both move.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { membershipRegistryKey, validateCoordinationName } from './lease';
import { assignment } from './partitions';
import {
  MEMBERSHIP_PING_SCRIPT,
  MEMBERSHIP_RESIGN_SCRIPT,
  MEMBERSHIP_SNAPSHOT_SCRIPT,
  MembershipRegistry,
  heartbeatExpiry,
  liveMembers,
  parseMemberReply,
} from './membership';

const repoRoot = join(__dirname, '..', '..', '..', '..', '..');

interface ScriptText {
  text: string;
  sha256: string;
}
interface ExpiryRow {
  nowMillis: number;
  ttlMillis: number;
  expiryMillis: number;
}
interface ExpiryRejectRow {
  nowMillis: number | boolean;
  ttlMillis: number | boolean;
  error: string;
}
interface MembersRow {
  nowMillis: number;
  entries: Array<[string, number]>;
  expected: string[];
}
interface MembersRejectRow {
  entries: Array<[string, unknown]>;
  nowMillis: number;
  error: string;
}
interface MembershipFixtures {
  membership: {
    heartbeatExpiry: ExpiryRow[];
    heartbeatExpiryRejects: ExpiryRejectRow[];
    liveMembers: MembersRow[];
    liveMembersRejects: MembersRejectRow[];
    scripts: {
      ping: ScriptText;
      snapshot: ScriptText;
      resign: ScriptText;
    };
    defaults: { group: string; key: string };
  };
}

const loadFixtures = (): MembershipFixtures =>
  JSON.parse(
    readFileSync(join(repoRoot, 'docs', 'fixtures', 'coordination_fixtures.json'), 'utf-8'),
  ) as MembershipFixtures;

const membership = loadFixtures().membership;

const sha256 = (text: string): string =>
  createHash('sha256').update(text, 'utf8').digest('hex');

/** The fixture pins Python messages; everything before ", got <repr>" is
 * language-neutral and compared, the repr tail is Python-shaped and is not
 * (same rule Part 11 set for renewDueMicrosRejects: the CONTRACT is "refuse
 * loudly at this boundary with this reason", not identical prose). */
const prefix = (error: string): string => error.split(', got ')[0] ?? error;

/* --------------------------------------------------------------------- */
/* the fake: a registry SERVER, not a mock - interprets scripts by exact */
/* text, so a drifted script fails here like it would fail on Redis.     */
/* --------------------------------------------------------------------- */

type ReplyShape = 'flat-strings' | 'int-scores';

class FakeRegistryServer {
  readonly zsets = new Map<string, Map<string, number>>();
  transportDown = false;
  replyShape: ReplyShape = 'flat-strings';

  private entries(key: string): Map<string, number> {
    let table = this.zsets.get(key);
    if (table === undefined) {
      table = new Map();
      this.zsets.set(key, table);
    }
    return table;
  }

  private flat(table: Map<string, number>): unknown[] {
    const out: unknown[] = [];
    for (const [member, expiry] of table) {
      out.push(member);
      out.push(this.replyShape === 'flat-strings' ? String(expiry) : expiry);
    }
    return out;
  }

  /** Port-shaped: the registry calls evalFlat(script, key, ...argv) -
   * exactly what IoredisCoordinationClient.evalFlat forwards. The one-key
   * protocol is structural in this signature: there IS no numkeys knob to
   * get wrong, which is the point of the port. */
  async evalFlat(script: string, key: string, ...argv: string[]): Promise<unknown> {
    if (this.transportDown) {
      throw new Error('transport down');
    }
    if (script === MEMBERSHIP_PING_SCRIPT) {
      const now = Number(argv[0]);
      const expiry = Number(argv[1]);
      const member = argv[2] as string;
      const table = this.entries(key);
      for (const [name, score] of table) {
        if (score <= now) table.delete(name);
      }
      const current = table.get(member);
      if (current === undefined || expiry > current) {
        table.set(member, expiry);
      }
      return this.flat(table);
    }
    if (script === MEMBERSHIP_SNAPSHOT_SCRIPT) {
      const table = this.zsets.get(key);
      if (table === undefined || table.size === 0) {
        return [];
      }
      return this.flat(table);
    }
    if (script === MEMBERSHIP_RESIGN_SCRIPT) {
      const table = this.entries(key);
      table.delete(argv[0] as string);
      return table.size;
    }
    throw new Error(`unknown script reached the fake: ${script.slice(0, 48)}`);
  }
}

const registryFor = (
  client: { evalFlat(script: string, key: string, ...argv: string[]): Promise<unknown> },
  member: string,
  ttlMillis?: number,
): MembershipRegistry =>
  new MembershipRegistry(client, { group: 'trade-execution', member, ttlMillis });

/* --------------------------------------------------------------------- */
/* 1. the pinned law                                                     */
/* --------------------------------------------------------------------- */

describe('membership law (fixture replay)', () => {
  it('replays every heartbeatExpiry row', () => {
    expect.assertions(membership.heartbeatExpiry.length);
    for (const row of membership.heartbeatExpiry) {
      expect(heartbeatExpiry(row.nowMillis, row.ttlMillis)).toBe(row.expiryMillis);
    }
  });

  it('refuses the rejected heartbeatExpiry rows with the same reasons', () => {
    for (const row of membership.heartbeatExpiryRejects) {
      expect(() =>
        heartbeatExpiry(
          row.nowMillis as unknown as number,
          row.ttlMillis as unknown as number,
        ),
      ).toThrow(prefix(row.error));
    }
    expect(membership.heartbeatExpiryRejects.length).toBe(4);
  });

  it('replays every liveMembers row (entries arrive as pairs)', () => {
    expect.assertions(membership.liveMembers.length);
    for (const row of membership.liveMembers) {
      const pairs: Array<readonly [string, number]> = row.entries.map(
        ([name, expiry]) => [name, expiry] as const,
      );
      expect([...liveMembers(pairs, row.nowMillis)]).toEqual(row.expected);
    }
  });

  it('refuses the rejected liveMembers rows with the same reasons', () => {
    for (const row of membership.liveMembersRejects) {
      const entry = row.entries[0] as readonly [string, unknown];
      expect(() => liveMembers([entry], row.nowMillis)).toThrow(prefix(row.error));
    }
    expect(membership.liveMembersRejects.length).toBe(4);
  });

  it('pins the strict-alive boundary in words the rows mean', () => {
    expect(liveMembers([['solo', 100]], 100)).toEqual([]);
    expect(liveMembers([['solo', 101]], 100)).toEqual(['solo']);
  });
});

/* --------------------------------------------------------------------- */
/* 2. the scripts and the key: byte parity with the Python module         */
/* --------------------------------------------------------------------- */

describe('membership scripts and key', () => {
  it('ship byte-identical Lua to the fixture (sha-pinned both sides)', () => {
    for (const [name, script] of [
      ['ping', MEMBERSHIP_PING_SCRIPT],
      ['snapshot', MEMBERSHIP_SNAPSHOT_SCRIPT],
      ['resign', MEMBERSHIP_RESIGN_SCRIPT],
    ] as const) {
      const entry = membership.scripts[name];
      expect(script).toBe(entry.text);
      expect(sha256(script)).toBe(entry.sha256);
    }
  });

  it('key builder matches the pinned default and the group grammar', () => {
    expect(membershipRegistryKey(membership.defaults.group)).toBe(membership.defaults.key);
    expect(() => membershipRegistryKey('has space')).not.toThrow(); // dumb builder, like Python's
    expect(() => validateCoordinationName('bad group!', 'coordination group')).toThrow(
      /wire token/,
    );
  });
});

/* --------------------------------------------------------------------- */
/* 3. the client contract                                                */
/* --------------------------------------------------------------------- */

describe('MembershipRegistry contract', () => {
  it('enforces its construction laws', () => {
    const server = new FakeRegistryServer();
    expect(
      () => new MembershipRegistry(server, { group: 'bad group!', member: 'm' }),
    ).toThrow(/coordination group .* is not a wire token/);
    expect(() => registryFor(server, 'has space')).toThrow(/is not a member token/);
    expect(() => registryFor(server, 'ok-member', 999)).toThrow(/flap on network jitter/);
    expect(() => registryFor(server, 'ok-member', true as unknown as number)).toThrow(
      /plain integer of milliseconds/,
    );
  });

  it('ping registers, and the reply is the live set', async () => {
    const server = new FakeRegistryServer();
    const reg = registryFor(server, 'worker-alpha');
    expect(await reg.ping(1_000)).toEqual(['worker-alpha']);
    expect(server.zsets.get(reg.key)?.get('worker-alpha')).toBe(heartbeatExpiry(1_000, 15_000));
  });

  it('the GT law makes stale replays harmless', async () => {
    const server = new FakeRegistryServer();
    const reg = registryFor(server, 'worker-alpha');
    await reg.ping(10_000);
    await reg.ping(9_000); // late replay with an EARLIER expiry
    expect(server.zsets.get(reg.key)?.get('worker-alpha')).toBe(heartbeatExpiry(10_000, 15_000));
  });

  it('ping propagates transport errors while members degrades to null', async () => {
    const server = new FakeRegistryServer();
    const reg = registryFor(server, 'worker-alpha');
    server.transportDown = true;
    await expect(reg.ping(1_000)).rejects.toThrow('transport down');
    expect(await reg.members(1_000)).toBeNull();
  });

  it('resign is best-effort', async () => {
    const server = new FakeRegistryServer();
    const reg = registryFor(server, 'worker-alpha');
    await reg.ping(1_000);
    expect(await reg.resign()).toBe(true);
    expect(await reg.members(1_000)).toEqual([]);
    server.transportDown = true;
    expect(await reg.resign()).toBe(false);
  });

  it('tolerates both reply shapes and is loud about garbage', () => {
    expect(parseMemberReply(['a', '101', 'b', 102], 100)).toEqual(['a', 'b']);
    expect(() => parseMemberReply(['unpaired'], 100)).toThrow(/odd number of elements/);
    expect(() => parseMemberReply('garbage', 100)).toThrow(/flat array/);
    expect(() => parseMemberReply(['a', '1.5'], 100)).toThrow(/\(str, int\) pair/);
  });
});

/* --------------------------------------------------------------------- */
/* 4. the fleet scenario: join, serve, die silently, reassign            */
/* --------------------------------------------------------------------- */

describe('membership drives real reassignment', () => {
  it('ages a silent worker out and hands its partitions over', async () => {
    const server = new FakeRegistryServer();
    const alpha = registryFor(server, 'worker-alpha', 30_000);
    const beta = registryFor(server, 'worker-beta', 30_000);
    const now = 1_000_000;

    expect(await alpha.ping(now)).toEqual(['worker-alpha']);
    expect(await beta.ping(now)).toEqual(['worker-alpha', 'worker-beta']);
    expect(await alpha.ping(now + 1_000)).toEqual(['worker-alpha', 'worker-beta']);

    // One zset per group, not per member: both registries address the same key.
    expect(alpha.key).toBe(beta.key);
    const table = assignmentTable(['worker-alpha', 'worker-beta']);
    expect(Object.keys(table).sort()).toEqual(['worker-alpha', 'worker-beta']);

    // Beta dies silently: no resign - the TTL is the only protocol, and
    // that is the case the whole design exists for.
    const staleAt = now + 1_000 + 30_000 + 1;
    expect(await alpha.ping(staleAt)).toEqual(['worker-alpha']);
    expect(await alpha.members(staleAt)).toEqual(['worker-alpha']);

    const after = assignmentTable(['worker-alpha']);
    expect(after).toEqual({ 'worker-alpha': [0, 1, 2, 3, 4, 5, 6, 7] });
  });
});

/** The 8-partition table through the REAL shared assignment primitive -
 * the reassignment test may not hand-copy the partition law. */
function assignmentTable(members: string[]): Record<string, number[]> {
  const table: Record<string, number[]> = {};
  for (const [member, partitions] of Object.entries(assignment(members, 8))) {
    table[member] = [...partitions];
  }
  return table;
}
