/**
 * Part 11 coordination: cross-language parity (replays
 * docs/fixtures/coordination_fixtures.json, generated by
 * libs/trading-core/scripts/gen_part11_fixtures.py from the Python
 * modules) plus behaviour of the Node-side lease primitives against a
 * fake Redis that, like the Python test double, only speaks the pinned
 * script texts.
 *
 * If a vector fails, do NOT regenerate the fixture to make it pass: fix
 * the side that drifted, regenerate from Python, and let both move.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  CLAIM_RELEASE_SCRIPT,
  CLAIM_RENEW_SCRIPT,
  type CoordinationRedis,
  LeaderElector,
  PartitionClaims,
  leaderLeaseKey,
  partitionClaimKey,
  renewDueMicros,
} from './lease';
import { crc32Utf8 } from './crc32';
import {
  MAX_PARTITIONS,
  assignment,
  movedByMembership,
  owns,
  partitionFor,
  partitionOwner,
} from './partitions';

const repoRoot = join(__dirname, '..', '..', '..', '..', '..');

/** zlib.crc32(b"abc") - hand-pinned from the published CRC-32 check value
 * (0x352F6DE2 = 891568578), not derived from either language's partition
 * function, so the parity chain has a human-checked root. */
const CRC_ABC = 891568578;

/* --------------------------------------------------------------------- */
/* typed view of the fixture file (compile-time drift detection)         */
/* --------------------------------------------------------------------- */

interface KeyVectorRow {
  name: string;
  key: string;
}
interface ClaimKeyRow {
  name: string;
  partition: number;
  key: string;
}
interface NameRejectRow {
  name: string;
  error: string;
}
interface PartitionVector {
  key: string;
  count: number;
  partition: number;
}
interface AssignmentRow {
  members: string[];
  count: number;
  table: Record<string, number[]>;
}
interface MovedRow {
  before: string[];
  after: string[];
  count: number;
  moved: Record<string, [string | null, string | null]>;
}
interface CountRejectRow {
  count: string;
  error: string;
}
interface MemberRejectRow {
  members: string[];
}
interface RenewDueRow {
  nowMicros: number;
  lastActionMicros: number;
  renewMillis: number;
  expected: boolean;
}
interface RenewDueRejectRow {
  error: string;
  renewMillis?: number;
  nowMicros?: string;
}
interface CrcRow {
  input: string;
  crc32: number;
}
interface TieRow {
  partition: number;
  score: number;
  members: string[];
  winner: string;
}
interface ConstructionRow {
  ttlMillis: number;
  renewMillis: number | null;
  ok: boolean;
  error?: string;
  derivedRenewMillis?: number;
}
interface ScriptText {
  text: string;
  sha256: string;
}
interface CoordinationFixtures {
  schema: string;
  keys: {
    leaderLease: KeyVectorRow[];
    partitionClaim: ClaimKeyRow[];
    partitionClaimRejects: NameRejectRow[];
    nameRejects: NameRejectRow[];
  };
  partitions: {
    maxPartitions: number;
    crc32: CrcRow[];
    tieBreak: TieRow[];
    partitionFor: PartitionVector[];
    assignments: AssignmentRow[];
    movedByMembership: MovedRow[];
    rejects: {
      counts: CountRejectRow[];
      keys: { key: string; count: number }[];
      members: MemberRejectRow[];
    };
  };
  lease: {
    renewDueMicros: RenewDueRow[];
    renewDueMicrosRejects: RenewDueRejectRow[];
    construction: ConstructionRow[];
    scripts: {
      claimRenew: ScriptText;
      claimRelease: ScriptText;
      lockExtend: ScriptText;
      lockRelease: ScriptText;
      note: string;
    };
    defaults: { defaultTtlMillis: number; defaultRetryDivisor: number };
  };
}

function loadFixtures(): CoordinationFixtures {
  const text = readFileSync(
    join(repoRoot, 'docs', 'fixtures', 'coordination_fixtures.json'),
    'utf-8',
  );
  return JSON.parse(text) as CoordinationFixtures;
}

const fixtures = loadFixtures();

const sha256 = (text: string): string =>
  createHash('sha256').update(text, 'utf8').digest('hex');

/* `repr()` spellings from the Python generator -> real values; the map is
 * explicit so a new reject row in the fixture is a compile-safe addition,
 * never a silently skipped one. */
const REPR_VALUES: Record<string, unknown> = {
  "0": 0,
  "-1": -1,
  "4097": 4097,
  "'8'": '8',
  true: true,
};

/* --------------------------------------------------------------------- */
/* parity                                                                */
/* --------------------------------------------------------------------- */

describe('Part 11 coordination fixtures (parity with wlct_trading)', () => {
  it('loads the committed fixture schema', () => {
    expect(fixtures.schema).toBe('part11-coordination-v1');
    expect(fixtures.partitions.maxPartitions).toBe(MAX_PARTITIONS);
  });

  it('mirrors the RedisKeys coordination key builders exactly', () => {
    for (const row of fixtures.keys.leaderLease) {
      expect({ name: row.name, key: leaderLeaseKey(row.name) }).toEqual(row);
    }
    for (const row of fixtures.keys.partitionClaim) {
      expect({
        name: row.name,
        partition: row.partition,
        key: partitionClaimKey(row.name, row.partition),
      }).toEqual(row);
    }
    for (const row of fixtures.keys.nameRejects) {
      expect(() => leaderLeaseKey(row.name)).toThrow(/wire token/);
    }
    for (const row of fixtures.keys.partitionClaimRejects) {
      expect(() => partitionClaimKey(row.name, -1)).toThrow(/non-negative/);
    }
  });

  it('partitions keys identically (crc32 % count, UTF-8)', () => {
    expect(fixtures.partitions.partitionFor.length).toBeGreaterThan(30);
    for (const row of fixtures.partitions.partitionFor) {
      expect({ ...row, partition: partitionFor(row.key, row.count) }).toEqual(row);
    }
    // (raw-CRC vectors live in their own test below)
  });

  it('rejects partition counts and keys the same way', () => {
    for (const row of fixtures.partitions.rejects.counts) {
      const value = REPR_VALUES[row.count];
      if (value === undefined) {
        throw new Error(`fixture count spelling ${row.count} has no probe mapping`);
      }
      expect(() => partitionFor('abc', value as number)).toThrow(row.error);
    }
    for (const row of fixtures.partitions.rejects.keys) {
      expect(() => partitionFor(row.key, row.count)).toThrow(/non-empty strings/);
    }
    for (const row of fixtures.partitions.rejects.members) {
      expect(() => assignment(row.members, 4)).toThrow(/wire token|duplicates/);
    }
  });

  it('computes identical rendezvous assignments', () => {
    expect(fixtures.partitions.assignments.length).toBe(20);
    for (const row of fixtures.partitions.assignments) {
      expect(assignment(row.members, row.count)).toEqual(row.table);
      // completeness + disjointness re-checked from the TS side, not just
      // asserted equal to a Python-produced table
      const seen = Object.values(row.table).flat();
      expect([...seen].sort((a, b) => a - b)).toEqual(
        Array.from({ length: row.count }, (_, i) => i),
      );
    }
    expect(assignment([], 8)).toEqual({});
    expect(partitionOwner(['m1', 'm2'], 3)).not.toBeNull();
    expect(partitionOwner([], 3)).toBeNull();
  });

  it('moves only the leaver\'s partitions (rendezvous property)', () => {
    for (const row of fixtures.partitions.movedByMembership) {
      const moved = movedByMembership(row.before, row.after, row.count);
      const asFixtureShape: Record<string, [string | null, string | null]> = {};
      for (const [partition, change] of Object.entries(moved)) {
        asFixtureShape[partition] = [change.before, change.after];
      }
      expect(asFixtureShape).toEqual(row.moved);
    }
    expect(movedByMembership(['a', 'b'], ['b', 'a'], 12)).toEqual({});
  });

  it('agrees on the renewal timing law, row for row', () => {
    for (const row of fixtures.lease.renewDueMicros) {
      expect(
        renewDueMicros({
          nowMicros: BigInt(row.nowMicros),
          lastActionMicros: BigInt(row.lastActionMicros),
          renewMillis: row.renewMillis,
        }),
      ).toBe(row.expected);
    }
    for (const row of fixtures.lease.renewDueMicrosRejects) {
      if (row.renewMillis !== undefined) {
        expect(() =>
          renewDueMicros({
            nowMicros: 1n,
            lastActionMicros: 0n,
            renewMillis: row.renewMillis as number,
          }),
        ).toThrow(row.error);
      } else {
        // Python rejects non-integer micros; TS rejects the same VALUES at
        // the same law boundary (mixing BigInt with a string/float/boolean
        // throws) - the contract is "refuse loudly", the exception class is
        // language-local, so the message is not compared byte-for-byte.
        expect(row.nowMicros).toBeDefined();
        expect(() =>
          renewDueMicros({
            nowMicros: (row.nowMicros as unknown as bigint) ?? 1n,
            lastActionMicros: 0n,
            renewMillis: 10,
          }),
        ).toThrow();
      }
    }
  });

  it('agrees on raw CRC-32 (the shared root primitive)', () => {
    for (const row of fixtures.partitions.crc32) {
      expect({ input: row.input, crc32: crc32Utf8(row.input) }).toEqual(row);
    }
    // human-checked root: the published CRC-32 check value for "abc"
    expect(crc32Utf8('abc')).toBe(CRC_ABC);
  });

  it('ties resolve to the lexicographically smallest member, both orders', () => {
    expect(fixtures.partitions.tieBreak.length).toBeGreaterThanOrEqual(4);
    for (const row of fixtures.partitions.tieBreak) {
      const [lo, hi] = row.members;
      if (lo === undefined || hi === undefined) {
        throw new Error('tie vector must hold exactly two members');
      }
      expect(lo < hi).toBe(true);
      expect(partitionOwner([hi, lo], row.partition)).toBe(row.winner);
      expect(partitionOwner([lo, hi], row.partition)).toBe(row.winner);
      expect(crc32Utf8(`${lo}|${row.partition}`)).toBe(row.score);
      expect(crc32Utf8(`${hi}|${row.partition}`)).toBe(row.score);
    }
  });

  it('shares lease construction rules, errors verbatim', () => {
    for (const row of fixtures.lease.construction) {
      const build = (): LeaderElector =>
        new LeaderElector(new FakeCoordinationRedis(), {
          name: 'parity-probe',
          ttlMillis: row.ttlMillis,
          ...(row.renewMillis === null ? {} : { renewMillis: row.renewMillis }),
        });
      if (row.ok) {
        expect(build).not.toThrow();
        if (row.derivedRenewMillis !== undefined) {
          expect(build().renewMillis).toBe(row.derivedRenewMillis);
        }
      } else {
        expect(build).toThrow(row.error as string);
      }
    }
    const defaults = new LeaderElector(new FakeCoordinationRedis(), {
      name: 'defaults',
    });
    expect(defaults.ttlMillis).toBe(fixtures.lease.defaults.defaultTtlMillis);
    expect(defaults.retryMillis).toBe(
      Math.max(
        250,
        Math.floor(
          fixtures.lease.defaults.defaultTtlMillis /
            fixtures.lease.defaults.defaultRetryDivisor,
        ),
      ),
    );
  });

  it('embeds byte-identical Lua scripts (text AND digest pinned)', () => {
    expect(CLAIM_RENEW_SCRIPT).toBe(fixtures.lease.scripts.claimRenew.text);
    expect(CLAIM_RELEASE_SCRIPT).toBe(fixtures.lease.scripts.claimRelease.text);
    for (const [name, constant, embedded] of [
      ['claimRenew', fixtures.lease.scripts.claimRenew, CLAIM_RENEW_SCRIPT],
      ['claimRelease', fixtures.lease.scripts.claimRelease, CLAIM_RELEASE_SCRIPT],
    ] as const) {
      expect({ name, digest: sha256(embedded) }).toEqual({
        name,
        digest: constant.sha256,
      });
    }
    // the Python note-claim: lock scripts equal claim scripts modulo
    // whitespace - re-verified here from the fixture texts themselves
    expect(fixtures.lease.scripts.lockExtend.text.trim()).toBe(
      fixtures.lease.scripts.claimRenew.text.trim(),
    );
    expect(fixtures.lease.scripts.lockRelease.text.trim()).toBe(
      fixtures.lease.scripts.claimRelease.text.trim(),
    );
  });

  it('owns() follows the table, absent member defers', () => {
    const table = assignment(['w1', 'w2', 'w3'], 12);
    for (const [member, parts] of Object.entries(table)) {
      const target = (parts as number[])[0];
      let probe = '';
      for (let n = 0; n < 4096; n += 1) {
        if (partitionFor(`acct-${n}`, 12) === target) {
          probe = `acct-${n}`;
          break;
        }
      }
      expect(owns(table, member, probe, 12)).toBe(true);
      for (const other of Object.keys(table)) {
        if (other !== member) {
          expect(owns(table, other, probe, 12)).toBe(false);
        }
      }
    }
    expect(owns({}, 'nope', 'key', 4)).toBe(false);
  });
});

/* --------------------------------------------------------------------- */
/* scripted fake: refuses any script text it does not know               */
/* --------------------------------------------------------------------- */

class FakeCoordinationRedis implements CoordinationRedis {
  store = new Map<string, { value: string; expiryMicros: number }>();
  micros = 1_700_000_000_000_000;
  failNextSet = false;
  failNextEval = false;
  evalCalls = 0;

  private live(name: string): string | null {
    const entry = this.store.get(name);
    if (entry === undefined) {
      return null;
    }
    if (entry.expiryMicros > 0 && this.micros >= entry.expiryMicros) {
      this.store.delete(name);
      return null;
    }
    return entry.value;
  }

  advanceMs(millis: number): void {
    // micros stay in the safe-integer band (start 1.7e15, tests advance by
    // seconds) - the parity table passes through BigInt separately, where
    // exactness of the fixture values matters
    this.micros += millis * 1_000;
  }

  async setIfAbsent(name: string, value: string, pxMillis: number): Promise<boolean> {
    if (this.failNextSet) {
      this.failNextSet = false;
      throw new Error('connection reset');
    }
    if (this.live(name) !== null) {
      return false;
    }
    this.store.set(name, { value, expiryMicros: this.micros + pxMillis * 1_000 });
    return true;
  }

  async get(name: string): Promise<string | null> {
    return this.live(name);
  }

  async eval(script: string, key: string, ...argv: string[]): Promise<number> {
    this.evalCalls += 1;
    if (this.failNextEval) {
      this.failNextEval = false;
      throw new Error('connection reset');
    }
    const kind =
      script === CLAIM_RENEW_SCRIPT
        ? 'renew'
        : script === CLAIM_RELEASE_SCRIPT
          ? 'release'
          : undefined;
    if (kind === undefined) {
      throw new Error(
        'FakeCoordinationRedis only speaks the shipped claim scripts; a new or ' +
          'edited script must be taught HERE deliberately, never silently',
      );
    }
    const current = this.live(key);
    if (current !== argv[0]) {
      return 0;
    }
    if (kind === 'release') {
      this.store.delete(key);
      return 1;
    }
    const entry = this.store.get(key) as { value: string; expiryMicros: number };
    this.store.set(key, {
      value: entry.value,
      expiryMicros: this.micros + Number(argv[1]) * 1_000,
    });
    return 1;
  }

  rawTtlMillis(name: string): number | null {
    const entry = this.store.get(name);
    if (entry === undefined) {
      return null;
    }
    return Math.max(0, entry.expiryMicros - this.micros) / 1_000;
  }
}

/* --------------------------------------------------------------------- */
/* behaviour                                                             */
/* --------------------------------------------------------------------- */

describe('LeaderElector (Node twin)', () => {
  it('first campaigner wins; second defers; re-campaign is a no-op', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    const e2 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    await expect(e1.tryCampaign()).resolves.toBe(true);
    await expect(e2.tryCampaign()).resolves.toBe(false);
    await expect(e1.tryCampaign()).resolves.toBe(true); // already leader
    expect(e1.key).toBe('wlct:trading:lock:leader:recon');
  });

  it('renewal re-dates the Redis-side TTL and counts itself', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    await e1.tryCampaign();
    redis.advanceMs(2_999);
    await expect(e1.renew()).resolves.toBe(true);
    expect(e1.state.renewals).toBe(1);
    expect(redis.rawTtlMillis(e1.key)).toBeGreaterThanOrEqual(9_000);
    expect(e1.state.sinceMicros).toBeGreaterThan(0n); // set at campaign
  });

  it('a TTL lapse demotes the stale holder at its next renew', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    const e2 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    await e1.tryCampaign();
    redis.advanceMs(10_001);
    expect(e1.isLeader).toBe(true); // belief survives until proof fails
    await expect(e1.renew()).resolves.toBe(false);
    expect(e1.isLeader).toBe(false);
    expect(e1.state.demotions).toBe(1);
    await expect(e2.tryCampaign()).resolves.toBe(true);
  });

  it('resign hands over immediately and second resign is a no-op', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    const e2 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    await e1.tryCampaign();
    await expect(e1.resign()).resolves.toBe(true);
    await expect(e2.tryCampaign()).resolves.toBe(true);
    expect(redis.store.get(e1.key)?.value).toBe(e2.state.token);
    await expect(e1.resign()).resolves.toBe(false);
    // resignation is a transition, not a demotion (Python-mirror law)
    expect(e1.state.demotions).toBe(0);
    expect(e2.state.demotions).toBe(0);
  });

  it('transport failures are recorded deferrals, never exceptions', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, { name: 'recon', ttlMillis: 10_000 });
    redis.failNextSet = true;
    await expect(e1.tryCampaign()).resolves.toBe(false);
    expect(e1.state.lastError).toBeTruthy();
    await expect(e1.tryCampaign()).resolves.toBe(true);
    expect(e1.state.lastError).toBeNull();
    redis.failNextEval = true;
    await expect(e1.renew()).resolves.toBe(false);
    expect(e1.isLeader).toBe(false); // cannot prove it holds -> not a holder
  });

  it('renewIfDue defers early ticks without touching Redis', async () => {
    const redis = new FakeCoordinationRedis();
    const e1 = new LeaderElector(redis, {
      name: 'tick',
      ttlMillis: 10_000,
      renewMillis: 3_000,
      now: () => redis.micros / 1000,
    });
    await e1.tryCampaign();
    const before = redis.evalCalls;
    redis.advanceMs(2_999);
    await expect(e1.renewIfDue()).resolves.toBe(true);
    expect(redis.evalCalls).toBe(before); // not due -> zero Redis traffic
    redis.advanceMs(1);
    await expect(e1.renewIfDue()).resolves.toBe(true);
    expect(redis.evalCalls).toBe(before + 1);
    expect(e1.state.renewals).toBe(1);
  });

  it('validates the half-TTL rule before touching Redis', () => {
    const redis = new FakeCoordinationRedis();
    expect(
      () => new LeaderElector(redis, { name: 'x', ttlMillis: 10_000, renewMillis: 5_000 }),
    ).toThrow(/half the lease TTL/);
    expect(() => new LeaderElector(redis, { name: 'x', ttlMillis: 999 })).toThrow(
      /below one second/,
    );
    expect(() => new LeaderElector(redis, { name: 'has space' })).toThrow(/wire token/);
  });
});

describe('PartitionClaims (Node twin)', () => {
  const claims = (redis: FakeCoordinationRedis, member: string): PartitionClaims =>
    new PartitionClaims(redis, { group: 'trade-execution', member, ttlMillis: 5_000 });

  it('claims, refuses strangers, and renews the owner silently', async () => {
    const redis = new FakeCoordinationRedis();
    const a = claims(redis, 'host1:1');
    const b = claims(redis, 'host2:1');
    await expect(a.claim(3)).resolves.toBe(true);
    await expect(b.claim(3)).resolves.toBe(false);
    await expect(a.claim(3)).resolves.toBe(true); // extend path
    await expect(a.holder(3)).resolves.toBe('host1:1');
    expect(a.keyFor(3)).toBe('wlct:trading:lock:partition:trade-execution:3');
  });

  it('expired claims simply become claimable', async () => {
    const redis = new FakeCoordinationRedis();
    const a = claims(redis, 'host1:1');
    const b = claims(redis, 'host2:1');
    await a.claim(3);
    redis.advanceMs(5_001);
    await expect(b.claim(3)).resolves.toBe(true);
    await expect(a.claim(3)).resolves.toBe(false); // no release needed by b
  });

  it('release is compare-and-delete', async () => {
    const redis = new FakeCoordinationRedis();
    const a = claims(redis, 'host1:1');
    const b = claims(redis, 'host2:1');
    await a.claim(0);
    await expect(b.release(0)).resolves.toBe(false); // stranger cannot release
    await expect(a.release(0)).resolves.toBe(true);
    await expect(a.holder(0)).resolves.toBeNull();
    await expect(b.claim(0)).resolves.toBe(true);
  });

  it('reconcile returns what was actually taken', async () => {
    const redis = new FakeCoordinationRedis();
    const a = claims(redis, 'host1:1');
    const b = claims(redis, 'host2:1');
    await b.claim(1);
    const held = await a.reconcile([0, 1, 2]);
    expect([...held].sort()).toEqual([0, 2]);
    await expect(a.reconcile([0, -1])).rejects.toThrow(/non-negative/);
  });

  it('transport failures are misses; validation refuses bad shapes', async () => {
    const redis = new FakeCoordinationRedis();
    const a = claims(redis, 'm');
    redis.failNextSet = true;
    await expect(a.claim(1)).resolves.toBe(false);
    expect(() => claims(redis, 'bad member')).toThrow(/member token/);
    expect(
      () =>
        new PartitionClaims(redis, { group: 'ok', member: 'm', ttlMillis: 999 }),
    ).toThrow(/one second/);
  });
});
