"""Redaction: recursive, structural, and hostile-input-tolerant.

The redactor is the last line between a log pipeline and a credential, so
the tests aim at the places real leaks actually come from: a secret nested
under an innocuous *key* (key-only filters miss it), a secret inside list
elements, a DSN inside an exception message, and a signed exchange query
string pasted into a message field. The JSON fixture keeps the Python and
TypeScript implementations pinned to the same answers.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from wlct_trading.observability.redaction import (
    REDACTED,
    is_sensitive_key,
    redact_exception,
    redact_mapping,
    redact_text,
    redact_value,
)

FIXTURES = Path(__file__).resolve().parents[3] / "docs" / "fixtures" / "observability_fixtures.json"


def test_key_rules() -> None:
    for key in ("api_key", "API-KEY", "apiKeySecret", "access_token", "password", "x-signature", "DATABASE_URL_DSN"):
        assert is_sensitive_key(key), key
    assert not is_sensitive_key("symbol")
    assert not is_sensitive_key("quantity")


def test_dict_lists_and_nesting_are_scrubbed() -> None:
    leaked = "sk_live_0123456789abcdefghij"
    source = {
        "order": {
            "id": "ord-1",
            "api_key": leaked,
            "meta": [{"token": "abc"}, {"safe": leaked}],
        },
        "amount": "1.5",
    }
    out = redact_value(source)
    assert out["order"]["api_key"] == REDACTED
    assert out["order"]["meta"][0]["token"] == REDACTED
    # Value-pattern sweep catches the key-less embedding in "safe".
    assert leaked not in json.dumps(out, default=str)
    assert out["amount"] == "1.5"
    # Input is never mutated.
    assert source["order"]["api_key"] == leaked


def test_value_patterns() -> None:
    assert REDACTED in redact_text("auth: Bearer abcdefghijklmnopqrstuvwxyz0123")
    assert REDACTED in redact_text(
        "-----BEGIN RSA PRIVATE KEY-----\nMIIEow\n-----END RSA PRIVATE KEY-----"
    )
    out = redact_text("connect postgresql://user:hunter2@db.internal:5432/wlct")
    assert "hunter2" not in out
    assert "db.internal:5432/wlct" in out  # host retained; credentials gone
    signed = redact_text("GET /api/v3/order?symbol=BTCUSDT&signature=DEADBEEFcafe1234")
    assert "DEADBEEFcafe1234" not in signed
    jwt = "header.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.9fKq-_2example_sig_x"
    assert REDACTED in redact_text(f"failed with token {jwt}")


def test_exception_summaries_are_safe() -> None:
    error = RuntimeError("failed to connect postgresql://admin:s3cret@db:5432/app")
    summary = redact_exception(error)
    assert summary["type"] == "RuntimeError"
    assert "s3cret" not in summary["message"]


def test_bytes_and_deep_nesting_bail_out() -> None:
    assert redact_value(b"\x00\x01secretish") == REDACTED
    deep: object = "bottom-token"
    for _ in range(40):
        deep = {"next": deep}
    out = redact_value(deep)
    assert "bottom-token" not in json.dumps(out)


def test_none_passthrough_and_mapping_helper() -> None:
    assert redact_mapping(None) is None
    mapped = redact_mapping({"ok": 1, "jwt": "x"})
    assert mapped is not None and mapped["ok"] == 1 and mapped["jwt"] == REDACTED


def test_object_fallback_stringifies_then_scrubs() -> None:
    class Weird:
        def __str__(self) -> str:
            return "inline api_key=AKIAIOSFODNN7EXAMPLE here"

    out = redact_value({"obj": Weird()})
    assert "AKIAIOSFODNN7EXAMPLE" not in str(out)


@pytest.mark.skipif(not FIXTURES.exists(), reason="generated by gen_observability_fixtures.py")
def test_shared_fixture_parity() -> None:
    doc = json.loads(FIXTURES.read_text(encoding="utf-8"))
    for case in doc["redaction"]["cases"]:
        if "key" in case:
            assert is_sensitive_key(case["key"]) is case["expected"], case
        else:
            got = redact_value(case["input"])
            assert got == case["expected"], case
            rendered = json.dumps(got)
            for secret in case.get("forbidden", []):
                assert secret not in rendered, (case, secret)


@pytest.mark.skipif(not FIXTURES.exists(), reason="generated by gen_observability_fixtures.py")
def test_shared_fixture_prometheus_vectors() -> None:
    doc = json.loads(FIXTURES.read_text(encoding="utf-8"))
    from wlct_trading.observability.metrics import ObservabilityRegistry, render_prometheus

    for vector in doc["prometheus"]["vectors"]:
        registry = ObservabilityRegistry(service=vector["service"])
        for family in vector["families"]:
            if family["type"] == "counter":
                registry.register_counter(family["name"], family["help"], *family["labels"])
            elif family["type"] == "gauge":
                registry.register_gauge(family["name"], family["help"], *family["labels"])
            else:
                registry.register_histogram(
                    family["name"], family["help"], tuple(family["labels"]), tuple(family["buckets"])
                )
            for record in family["record"]:
                kind = record["op"]
                if kind == "inc":
                    registry.inc(family["name"], record["labels"], record.get("amount", 1))
                elif kind == "set":
                    registry.set_gauge(family["name"], record["labels"], record["value"])
                else:
                    registry.observe_micros(family["name"], record["labels"], record["micros"])
        assert render_prometheus(registry) == vector["text"], vector["name"]
