"""Generate the Part 11 row-level-security artefacts from schema.prisma.

WHY A GENERATOR AND NOT A HAND-WRITTEN MIGRATION: the tenant-table set is
exactly "models whose `tenantId` column is non-nullable" - and that set is a
property of the schema, which changes with every part. A hand-maintained SQL
list rots silently: the next part adds an `orders`-like table, forgets the
policy, and the defence layer quietly defends one table less than everyone
believes it covers. Here the drift is impossible by construction: rerun this
generator and the coverage JSON, the migration, and the enable/disable
scripts agree with the schema, and the API spec (rls-coverage.spec.ts)
re-parses the schema on every test run and refuses the difference.

Emitted artefacts (all complete, all deterministic - sorted, fixed header):

  apps/api/prisma/migrations/<stamp>_part11_row_level_security/migration.sql
      functions + one policy per covered table. Strictly additive. It
      DELIBERATELY does not ENABLE row-level security: enabling while any
      write path still omits `set_config('app.tenant_id', …)` converts a
      deployment misconfiguration into an outage - so enablement is the
      separate, checklist-gated `prisma/rls/enable.sql` DBA step.

  apps/api/prisma/rls/enable.sql   - per-table ENABLE + FORCE + the
      pre-flight checklist and post-enable verification queries.
  apps/api/prisma/rls/disable.sql  - the exact inverse (rollback path).
  apps/api/prisma/rls/grant.sql    - the one catalog read the enablement audit
      needs, and the file the engine's 503 message names. It exists because an
      operator told to "apply the grant" has to be able to open something; a
      refusal that points at a file nobody wrote is a second incident.
  apps/api/prisma/rls/rls_coverage.json - the machine-readable truth the
      spec pins.

Excluded tables (nullable tenantId: roles, subscription_plans, audit_logs,
security_events, kill_switches, ops_alerts, ops_incidents) carry
platform-wide rows where a strict tenant policy would hide rows that are not
anybody's secret, while the tenant-bearing rows stay app-filtered by the
tenant-scoped factory; the exclusion is stated in every artefact and the
coverage JSON rather than being an omission.

Run: `python3 scripts/gen_part11_rls.py [--stamp YYYYMMDDHHMMSS]` from the
repository root. The stamp exists so CI/re-runs target one migration folder.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] if "__file__" in globals() else Path(".")
SCHEMA = ROOT / "apps" / "api" / "prisma" / "schema.prisma"
MIGRATIONS = ROOT / "apps" / "api" / "prisma" / "migrations"
RLS_DIR = ROOT / "apps" / "api" / "prisma" / "rls"

FUNCTION_NAME = "wlct_current_tenant_id"
POLICY_NAME = "tenant_isolation"


def parse_tenant_tables() -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """(covered, excluded) by (table, model) sorted by table name."""
    text = SCHEMA.read_text(encoding="utf-8")
    covered: list[tuple[str, str]] = []
    excluded: list[tuple[str, str]] = []
    for m in re.finditer(r"^model (\w+) \{(.*?)^\}", text, re.M | re.S):
        name, body = m.group(1), m.group(2)
        map_m = re.search(r'@@map\("([^"]+)"\)', body)
        if map_m is None:
            continue
        table = map_m.group(1)
        if re.search(r"^\s*tenantId\s+String\s+@", body, re.M):
            uuid_col = re.search(r"^\s*tenantId\s+String\s+@[^\n]*@db\.Uuid", body, re.M)
            if uuid_col is None:
                raise SystemExit(
                    f"{name}: tenantId is non-nullable but not @db.Uuid - the policy "
                    "function returns uuid; decide the cast deliberately before shipping"
                )
            covered.append((table, name))
        elif re.search(r"^\s*tenantId\s+String\?\s+@", body, re.M):
            excluded.append((table, name))
    return sorted(covered), sorted(excluded)


def header(what: str, stamp: str) -> str:
    return f"""-- Part 11 ({what}). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: {stamp}.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.
"""


def build_migration(covered: list[tuple[str, str]], excluded: list[tuple[str, str]], stamp: str) -> str:
    lines = [header("migration: functions + policies (NOT enabling)", stamp)]
    lines.append(f"""
-- The single source of the request's tenant, read from the transaction-local
-- GUC that PrismaService.withTenantRls() sets via set_config(..., true).
-- STABLE so the planner evaluates it once per query, not per row.
CREATE OR REPLACE FUNCTION {FUNCTION_NAME}() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;
""")
    for table, model in covered:
        lines.append(f"""
-- {model}
CREATE POLICY {POLICY_NAME} ON "{table}"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = {FUNCTION_NAME}())
    WITH CHECK (tenant_id = {FUNCTION_NAME}());""")
    lines.append("")
    lines.append(
        """
-- Deliberately NOT enabled here. `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`
-- (and FORCE) is the prisma/rls/enable.sql DBA step, run only after the
-- pre-flight checklist there passes - enabling before every write path
-- adopts withTenantRls() turns defence into outage, and that trade is made
-- once, on purpose, by a human with the checklist.
--
-- Excluded by design (nullable tenantId; platform-scoped rows):
"""
    )
    for table, model in excluded:
        lines.append(f"--   {table:<34s} ({model})")
    lines.append(
        """-- Their tenant-bearing rows remain filtered by the tenant-scoped factory;
-- a strict policy here would hide the NULL-tenant platform rows that are
-- nobody's cross-tenant secret. The exclusion is a decision, listed in
-- rls_coverage.json and pinned by rls-coverage.spec.ts - never an oversight.
"""
    )
    return "\n".join(lines).replace("\n\n\n", "\n\n").rstrip() + "\n"


def build_enable(covered: list[tuple[str, str]], excluded: list[tuple[str, str]], stamp: str) -> str:
    tables = "\n".join(
        f'ALTER TABLE "{t}" ENABLE ROW LEVEL SECURITY;\n'
        f'ALTER TABLE "{t}" FORCE ROW LEVEL SECURITY;'
        for t, _ in covered
    )
    checks = "\n".join(f'--   SELECT count(*) FROM "{t}";' for t, _ in covered[:3])
    return f"""{header("enable: the DBA step", stamp)}
-- PRE-FLIGHT CHECKLIST - all of it, or do not run this file:
--
--  1. Every API write/read path for a covered table runs inside
--     PrismaService.withTenantRls(tenantId, ...) (which issues
--     set_config('app.tenant_id', $1, true) as the transaction's first
--     statement). Grep the module for direct prisma.<model> usage outside
--     the scoped client as part of the review.
--  2. The application role has neither BYPASSRLS nor superuser:
--        SELECT rolname, rolbypassrls, rolsuper
--        FROM pg_roles WHERE rolname = current_user;
--     FORCE below covers the table OWNER; it does not cover those two
--     privileges, and a role that has them makes the whole exercise
--     theatre. Deployment roles get exactly what they need, nothing more.
--  3. Queue-side writers (audit, alerts, incidents - the excluded nullable
--     tables) are confirmed unaffected: they are not covered here.
--  4. Rollback rehearsed: prisma/rls/disable.sql returns to today's state
--     exactly (NO FORCE, DISABLE, then the migration's objects stay
--     defined and inert).
--  5. Run at low traffic. Enabling is a catalog flip per table; in-flight
--     transactions without the GUC start seeing zero rows immediately -
--     which is the point, and the reason it is a scheduled operation.

-- --- covered tables ({len(covered)}) -------------------------------------------
{tables}

-- --- post-enable verification (manual, expect each count to match the
-- --- seeded tenant's own rows under that tenant's GUC, and zero without) --
-- BEGIN; SELECT set_config('app.tenant_id', '<tenant-uuid>', true);
{checks}
-- ROLLBACK;
-- Without the GUC, every covered table must read 0 rows as the app role.

-- Excluded (platform-scoped, nullable tenantId) - intentionally untouched:
{chr(10).join(f"--   {t} ({m})" for t, m in excluded)}
"""


def build_disable(covered: list[tuple[str, str]], stamp: str) -> str:
    tables = "\n".join(
        f'ALTER TABLE "{t}" NO FORCE ROW LEVEL SECURITY;\n'
        f'ALTER TABLE "{t}" DISABLE ROW LEVEL SECURITY;'
        for t, _ in covered
    )
    return f"""{header("disable: the exact inverse of enable.sql", stamp)}
-- Policies and the GUC function remain defined (inert while RLS is off), so
-- this file is one-way reversible by re-running enable.sql once the
-- checklist passes again.
{tables}
"""


def build_grant(stamp: str) -> str:
    """The catalog read the enablement audit performs, and nothing else.

    Kept inside the generator rather than hand-written into `prisma/rls/` for the same reason the
    other three artefacts are: that directory is reproducible from `schema.prisma`, and a
    hand-authored file in it would be the one file a rerun either deletes or contradicts.
    """
    return f"""{header("grant: the catalog read the enablement audit needs", stamp)}
-- WHY THIS FILE EXISTS. The enablement audit asks the database who is connected and whether that
-- role can walk past row-level security:
--
--     SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user;
--
-- When that query returns nothing the audit refuses (ProbeRoleUnknown -> 503
-- ENABLEMENT_ROLE_UNKNOWN in services/execution-engine/app/routers/enablement.py) instead of
-- reading "no row" as "no bypass". `pg_roles` is readable by PUBLIC in a vanilla cluster, so the
-- clusters that trip this are the ones that hardened their catalog by revoking PUBLIC read -
-- which is precisely where the grant below is owed rather than noise.
--
-- WHAT IT GRANTS, in full: SELECT on one catalog view. Not BYPASSRLS, not superuser, not SELECT on
-- any tenant table. A role that has to find out whether it holds a privilege is not thereby given
-- the privilege, and enable.sql's pre-flight refuses a role that holds either - so granting either
-- here would make this file the thing it exists to detect.

-- The grantee is whatever your DATABASE_URL names. `wlct_app` is the role this repository's own
-- .env.example DSN uses, and nothing in this tree decides a deployment's role name for it; change
-- the one line below on a cluster that calls the role something else. Run the file through psql,
-- since \\set is a psql meta-command and not SQL.
\\set approle wlct_app

GRANT SELECT ON pg_catalog.pg_roles TO :"approle";

-- --- post-grant verification, as the app role, in one transaction ------------------------------
-- BEGIN;
-- SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user;
-- ROLLBACK;
-- One row with both flags false is the state the audit grades. Zero rows keeps the 503, and a row
-- with either flag true is caught by enable.sql's checklist before a policy is enabled - the
-- ordering is deliberate, because a bypass discovered after enablement is an outage report and a
-- bypass discovered before it is a declined deployment.

-- --- inverse -----------------------------------------------------------------------------------
-- REVOKE SELECT ON pg_catalog.pg_roles FROM :"approle";
-- Only to undo this file. A cluster that revoked PUBLIC read on the catalog views does not need
-- this revoke to return to its own baseline, and running it there would leave the audit unable to
-- read the flag it is supposed to grade - the 503 is the safer outcome of the two.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stamp", default="20260913120000")
    args = parser.parse_args()

    covered, excluded = parse_tenant_tables()
    if len(covered) < 20:
        raise SystemExit(f"schema parse produced only {len(covered)} covered tables - refusing")

    mig_dir = MIGRATIONS / f"{args.stamp}_part11_row_level_security"
    mig_dir.mkdir(parents=True, exist_ok=True)
    (mig_dir / "migration.sql").write_text(build_migration(covered, excluded, args.stamp), encoding="utf-8")
    RLS_DIR.mkdir(parents=True, exist_ok=True)
    (RLS_DIR / "enable.sql").write_text(build_enable(covered, excluded, args.stamp), encoding="utf-8")
    (RLS_DIR / "disable.sql").write_text(build_disable(covered, args.stamp), encoding="utf-8")
    (RLS_DIR / "grant.sql").write_text(build_grant(args.stamp), encoding="utf-8")
    (RLS_DIR / "rls_coverage.json").write_text(
        json.dumps(
            {
                "schema": "part11-rls-coverage-v1",
                "stamp": args.stamp,
                "policyName": POLICY_NAME,
                "functionName": FUNCTION_NAME,
                "covered": [{"table": t, "model": m} for t, m in covered],
                "excluded": [{"table": t, "model": m} for t, m in excluded],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"covered: {len(covered)} tables, excluded: {len(excluded)}")
    print(f"wrote {mig_dir}/migration.sql, {RLS_DIR}/{{enable,disable,grant}}.sql, rls_coverage.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
