import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { validateEnv, EnvValidationError } from '@wlct/config';
import {
  NON_WILDCARD_PERMISSIONS,
  Permission,
  SYSTEM_ROLE_DEFINITIONS,
  SystemRole,
  hasPermission,
} from '@wlct/shared-types';
import { validate } from 'class-validator';
import { plainToInstance } from 'class-transformer';

import {
  DECIMAL_STRING_PATTERN,
  PROTECTION_ACTIONS,
  PROTECTION_CLEAR_CONFIRMATION,
  RISK_CONSOLE_ENGAGE_SCOPES,
  RISK_RULE_IDS,
  RISK_RULE_UNITS,
  RISK_SWITCH_STATUSES,
  RISK_SWITCH_TRANSITIONS,
  RATE_WINDOWS_MICROS,
  WIDEN_CONFIRMATION,
} from './risk.constants';
import {
  canonicalDecimalString,
  canonicalJson,
  compareDecimalStrings,
  sha256Hex,
} from './risk.digest';
import {
  ClearRiskSwitchDto,
  EngageRiskSwitchDto,
  RollbackRiskPolicyDto,
  UpdateRiskPolicyDto,
} from './dto/risk.dto';

/**
 * Part 8 safety tests for the risk control plane.
 *
 * Three families of assertions, in order of how much they are worth:
 *
 *  1. CROSS-LANGUAGE PARITY. The TypeScript constants and canonicalisation
 *     are hand-written replicas of Python truth (`wlct_trading.enums`,
 *     `wlct_trading.risk.configuration`). Two hand-written copies of one
 *     rule drift, and the drift is silent: the API would happily publish a
 *     configuration whose digest the engine computes differently, and every
 *     snapshot would refuse to bind. The fixtures under docs/fixtures are
 *     GENERATED by `libs/trading-core/scripts/gen_risk_digest_fixtures.py`,
 *     and the Python source is additionally parsed live so a constant edit
 *     on one side fails this suite in CI, not in production.
 *
 *  2. WHAT THIS SURFACE CANNOT DO, asserted by reading the shipped source:
 *     no PUT/PATCH/DELETE routes, no order execution or approval anywhere in
 *     the module, no writes to order tables, no execution-queue traffic, and
 *     the two typed-confirmation phrases are different strings that each
 *     appear exactly where they must.
 *
 *  3. THE ENVIRONMENT GATE. `RISK_FAIL_CLOSED=false` has no legal value
 *     anywhere - not in test, not in production - and the window orderings
 *     that would make a ceiling unreachable are refused at boot.
 *
 * No database, no network, no venue, no secrets.
 */

function baseEnv(overrides: Record<string, string> = {}): Record<string, string> {
  return {
    NODE_ENV: 'test',
    DATABASE_URL: 'postgresql://user:pass@localhost:5432/db?schema=public',
    DIRECT_DATABASE_URL: 'postgresql://user:pass@localhost:5432/db?schema=public',
    REDIS_URL: 'redis://localhost:6379/0',
    JWT_ACCESS_SECRET: 'a'.repeat(48),
    JWT_REFRESH_SECRET: 'b'.repeat(48),
    ENCRYPTION_MASTER_KEY_BASE64: Buffer.alloc(32, 7).toString('base64'),
    BLIND_INDEX_KEY_BASE64: Buffer.alloc(32, 9).toString('base64'),
    INTERNAL_SERVICE_TOKEN: 'c'.repeat(32),
    EXCHANGE_WEBHOOK_SIGNING_SECRET: 'd'.repeat(32),
    ...overrides,
  };
}

function failurePaths(env: Record<string, string>): string[] {
  try {
    validateEnv(env);
  } catch (error) {
    if (error instanceof EnvValidationError) {
      return error.failures.map((entry) => entry.path);
    }
    throw error;
  }
  throw new Error('Expected validation to fail, but it succeeded.');
}

// -- Python-side truth, read live -------------------------------------------

const TRADING_CORE_SRC = join(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  '..',
  'libs',
  'trading-core',
  'wlct_trading',
);

const pythonEnumsSource = readFileSync(join(TRADING_CORE_SRC, 'enums.py'), 'utf-8');

function parseRuleOrder(): string[] {
  const block = /RISK_RULE_ORDER: tuple\[RiskRuleId, \.\.\.\] = \(([\s\S]*?)\n\)/u.exec(
    pythonEnumsSource,
  );
  if (!block) {
    throw new Error('Could not locate RISK_RULE_ORDER in enums.py - did the shape change?');
  }
  return [...block[1].matchAll(/RiskRuleId\.([A-Z_]+)/gu)].map((match) => match[1]);
}

function parseRuleUnits(): Record<string, string[]> {
  const start = pythonEnumsSource.indexOf('RISK_RULE_UNITS: dict');
  const end = pythonEnumsSource.indexOf('\n}', start);
  if (start < 0 || end < 0) {
    throw new Error('Could not locate RISK_RULE_UNITS in enums.py');
  }
  const block = pythonEnumsSource.slice(start, end);
  const out: Record<string, string[]> = {};
  for (const match of block.matchAll(
    /RiskRuleId\.([A-Z_]+):\s*frozenset\(\s*\{([^}]*)\}\s*\)/gu,
  )) {
    const units = [...match[2].matchAll(/RiskLimitUnit\.([A-Z_]+)/gu)].map((u) => u[1]);
    out[match[1]] = [...units].sort();
  }
  return out;
}

function parseSwitchTransitions(): Record<string, string[]> {
  const start = pythonEnumsSource.indexOf('RISK_SWITCH_TRANSITIONS: dict');
  const end = pythonEnumsSource.indexOf('\n}', start);
  if (start < 0 || end < 0) {
    throw new Error('Could not locate RISK_SWITCH_TRANSITIONS in enums.py');
  }
  const block = pythonEnumsSource.slice(start, end);
  const out: Record<string, string[]> = {};
  for (const match of block.matchAll(
    /RiskSwitchStatus\.([A-Z_]+):\s*frozenset\(\s*\{([^}]*)\}\s*\)/gu,
  )) {
    const targets = [...match[2].matchAll(/RiskSwitchStatus\.([A-Z_]+)/gu)].map((t) => t[1]);
    out[match[1]] = [...targets].sort();
  }
  return out;
}

// -- fixtures, generated from the real Python module -------------------------

interface DigestFixture {
  version: number;
  ruleOrder: string[];
  ruleUnits: Record<string, string[]>;
  switchTransitions: Record<string, string[]>;
  decimalNormalizations: { input: string; normalized: string; pythonStoredRaw: string }[];
  decimalComparisons: { left: string; right: string; sign: number }[];
  cases: {
    name: string;
    canonicalPayload: Record<string, unknown>;
    canonicalJson: string;
    digest: string;
  }[];
}

const fixtures = JSON.parse(
  readFileSync(join(__dirname, '..', '..', '..', '..', '..', 'docs', 'fixtures', 'risk_digest_fixtures.json'), 'utf-8'),
) as DigestFixture;

describe('Part 8 - risk environment gate', () => {
  it('ships fail-closed and engine-on as the only test-environment defaults', () => {
    const env = validateEnv(baseEnv());
    expect(env.RISK_FAIL_CLOSED).toBe(true);
    expect(env.RISK_ENGINE_ENABLED).toBe(true);
    expect(env.MAX_RISK_STATE_AGE_MS).toBe(2000);
    expect(env.RISK_SNAPSHOT_REFRESH_MS).toBe(250);
    expect(env.RISK_EVENTS_RETENTION_DAYS).toBe(365);
  });

  it('refuses RISK_FAIL_CLOSED=false everywhere, including tests and development', () => {
    expect(failurePaths(baseEnv({ RISK_FAIL_CLOSED: 'false' }))).toContain('RISK_FAIL_CLOSED');
    expect(
      failurePaths({ ...baseEnv({ RISK_FAIL_CLOSED: 'false' }), NODE_ENV: 'development' }),
    ).toContain('RISK_FAIL_CLOSED');
  });

  it('refuses a snapshot cadence that cannot outpace the staleness budget', () => {
    expect(
      failurePaths(
        baseEnv({ RISK_SNAPSHOT_REFRESH_MS: '2000', MAX_RISK_STATE_AGE_MS: '2000' }),
      ),
    ).toContain('RISK_SNAPSHOT_REFRESH_MS');
  });

  it('refuses per-minute budgets smaller than the per-second budgets', () => {
    expect(failurePaths(baseEnv({ MAX_ORDERS_PER_MINUTE: '1', MAX_ORDERS_PER_SECOND: '2' }))).toContain(
      'MAX_ORDERS_PER_MINUTE',
    );
    expect(
      failurePaths(baseEnv({ MAX_CANCELS_PER_MINUTE: '1', MAX_CANCELS_PER_SECOND: '2' })),
    ).toContain('MAX_CANCELS_PER_MINUTE');
  });

  it('refuses to boot production with the extended engine disabled', () => {
    expect(
      failurePaths(baseEnv({ NODE_ENV: 'production', RISK_ENGINE_ENABLED: 'false' })),
    ).toContain('RISK_ENGINE_ENABLED');
  });
});

describe('Part 8 - constants parity with the Python source', () => {
  it('the TS rule catalog is exactly RISK_RULE_ORDER, in order', () => {
    expect([...RISK_RULE_IDS]).toEqual(parseRuleOrder());
    expect(RISK_RULE_IDS.length).toBeGreaterThanOrEqual(20);
  });

  it('unit admission matches RISK_RULE_UNITS entry for entry', () => {
    const pythonUnits = parseRuleUnits();
    expect(Object.keys(pythonUnits).sort()).toEqual([...RISK_RULE_IDS].sort());
    for (const rule of RISK_RULE_IDS) {
      expect([...(RISK_RULE_UNITS[rule] ?? [])].sort()).toEqual(pythonUnits[rule]);
    }
  });

  it('the switch lifecycle table matches RISK_SWITCH_TRANSITIONS exactly', () => {
    const python = parseSwitchTransitions();
    expect(Object.keys(python).sort()).toEqual([...RISK_SWITCH_STATUSES].sort());
    for (const status of RISK_SWITCH_STATUSES) {
      expect([...RISK_SWITCH_TRANSITIONS[status]].sort()).toEqual(python[status]);
    }
    // Readings of specific policy decisions, asserted directly so a table
    // edit that keeps the SHAPE but changes the MEANING still fails:
    expect(python.TRIGGERED).toContain('ACKNOWLEDGED');
    expect(python.TRIGGERED).not.toContain('INACTIVE'); // no silent auto-clear
    expect(python.CLEARED).toEqual(['INACTIVE']);
  });

  it('the fixture document (generated from Python) agrees with the live parse', () => {
    expect(fixtures.ruleOrder).toEqual(parseRuleOrder());
    expect(fixtures.switchTransitions).toEqual(parseSwitchTransitions());
    const live = parseRuleUnits();
    for (const [rule, units] of Object.entries(fixtures.ruleUnits)) {
      expect([...units].sort()).toEqual([...(live[rule] ?? [])]);
    }
  });

  it('rate windows are the two Python-admitted ones', () => {
    expect([...RATE_WINDOWS_MICROS]).toEqual([1_000_000, 60_000_000]);
    expect(PROTECTION_ACTIONS).toContain('BLOCK_NEW_RISK');
    // No liquidation member exists, in either language, ever:
    expect(PROTECTION_ACTIONS.some((action) => action.includes('LIQUIDAT'))).toBe(false);
    // ...and no enum MEMBER with that name (the docstring may mention the
    // word; a member declaration must not exist):
    expect(pythonEnumsSource).not.toMatch(/LIQUIDAT\w*\s*=\s*['"]/u);
  });
});

describe('Part 8 - canonicalisation parity with Python (fixture-driven)', () => {
  it('canonicalDecimalString replicates Decimal(value).normalize() string form', () => {
    for (const c of fixtures.decimalNormalizations) {
      expect(canonicalDecimalString(c.input)).toBe(c.normalized);
      // Fixed point over the fixture's own forms: a canonical PLAIN
      // decimal re-canonicalises to itself (what the stored document
      // guarantees for the Python loader's str(Decimal(v)) round-trip).
      if (new RegExp(DECIMAL_STRING_PATTERN).test(c.normalized)) {
        expect(canonicalDecimalString(c.normalized)).toBe(c.normalized);
      }
      // Python stores str(Decimal(input)) when a document is built
      // Python-side. If that stored form is still a PLAIN decimal the
      // canonicaliser reproduces the fixture answer; if Python already
      // rendered it in scientific form, it IS the canonical answer:
      if (new RegExp(DECIMAL_STRING_PATTERN).test(c.pythonStoredRaw)) {
        expect(canonicalDecimalString(c.pythonStoredRaw)).toBe(c.normalized);
      } else {
        expect(c.pythonStoredRaw).toBe(c.normalized);
      }
    }
  });

  it('rejects inputs the plain-decimal gate must never accept', () => {
    expect(canonicalDecimalString('1e3')).toBeNull();
    expect(canonicalDecimalString(' 5')).toBe('5'); // trims, like Decimal(); the DTO pattern is the gate
    expect(canonicalDecimalString('1,000')).toBeNull();
    expect(canonicalDecimalString('')).toBeNull();
    expect(canonicalDecimalString('12.3.4')).toBeNull();
    // And the DTO pattern refuses floats-as-text exponents too:
    const re = new RegExp(DECIMAL_STRING_PATTERN);
    expect(re.test('1e3')).toBe(false);
    expect(re.test('5000')).toBe(true);
    expect(re.test('-0.25')).toBe(true);
    expect(re.test('007')).toBe(true); // leading zeros are Python-legal; normalisation strips them
  });

  it('compareDecimalStrings agrees with Python Decimal comparison', () => {
    for (const c of fixtures.decimalComparisons) {
      expect(compareDecimalStrings(c.left, c.right)).toBe(c.sign);
      expect(compareDecimalStrings(c.right, c.left)).toBe(c.sign === 0 ? 0 : -c.sign);
    }
  });

  it('canonicalJson + sha256Hex reproduce Python canonical_json and digest, per case', () => {
    expect(fixtures.cases.length).toBeGreaterThanOrEqual(4);
    for (const fixtureCase of fixtures.cases) {
      const json = canonicalJson(fixtureCase.canonicalPayload);
      expect(json).toBe(fixtureCase.canonicalJson);
      expect(sha256Hex(json)).toBe(fixtureCase.digest);
      // Independent oracle for the hash itself (node crypto, same input):
      expect(createHash('sha256').update(Buffer.from(json, 'utf-8')).digest('hex')).toBe(
        fixtureCase.digest,
      );
    }
  });

  it('canonicalJson serialises exactly like json.dumps(sort_keys, separators, ensure_ascii)', () => {
    // Spot cases that the fixtures only cover collectively: key sort is
    // recursive, non-ASCII is escaped, and no whitespace appears anywhere.
    expect(canonicalJson({ b: 1, a: { d: true, c: null } })).toBe('{"a":{"c":null,"d":true},"b":1}');
    expect(canonicalJson({ note: 'naïve ✓' })).toBe('{"note":"na\\u00efve \\u2713"}');
    expect(canonicalJson([1, 'two', false, null])).toBe('[1,"two",false,null]');
    // Floats must never appear in a canonical document - the serializer
    // refuses rather than rounding something through double precision:
    expect(() => canonicalJson({ value: 1.5 })).toThrow(/non-integer/u);
  });
});

describe('Part 8 - what the risk surface cannot do (source scan)', () => {
  const moduleDir = join(__dirname);
  const moduleFiles = [
    'risk.controller.ts',
    'risk.module.ts',
    'risk-policy.service.ts',
    'risk-protection.service.ts',
    'risk-state.service.ts',
    'risk.mapper.ts',
    'risk.digest.ts',
    'dto/risk.dto.ts',
  ];
  const sources = new Map(
    moduleFiles.map((file) => [file, readFileSync(join(moduleDir, file), 'utf-8')]),
  );

  it('has no PUT, PATCH or DELETE routes anywhere in the module', () => {
    for (const [file, source] of sources) {
      expect({ file, hits: source.match(/@(Put|Patch|Delete)\(/gu) ?? [] }).toEqual({
        file,
        hits: [],
      });
    }
    const controller = sources.get('risk.controller.ts') ?? '';
    expect(controller).toMatch(/@Get\(/u);
    expect(controller).toMatch(/@Post\(/u);
  });

  it('contains no order execution, order approval, or execution-module coupling', () => {
    const banned = [
      /from '\.\.\/execution/u,
      /\bExecutionService\b/u,
      /\bsubmitOrder\b/u,
      /\border[-_]?approval/iu,
      /\bapproveOrder\b/u,
      /\bplaceOrder\b/u,
      /prisma\.order\b/u,
      /prisma\.fillRecord\b/u,
      /QUEUE_NAMES\.EXECUTION/u,
      /execution-queue/u,
    ];
    for (const [file, source] of sources) {
      for (const pattern of banned) {
        expect({ file, pattern: pattern.source, hit: pattern.test(source) }).toEqual({
          file,
          pattern: pattern.source,
          hit: false,
        });
      }
    }
  });

  it('the two typed confirmations are distinct phrases wired where they belong', () => {
    expect(PROTECTION_CLEAR_CONFIRMATION).not.toBe(WIDEN_CONFIRMATION);
    expect(sources.get('risk-policy.service.ts')).toContain('WIDEN_CONFIRMATION');
    expect(sources.get('risk-protection.service.ts')).toContain('PROTECTION_CLEAR_CONFIRMATION');
    expect(sources.get('dto/risk.dto.ts')).toContain('PROTECTION_CLEAR_CONFIRMATION');
    expect(sources.get('dto/risk.dto.ts')).toContain('WIDEN_CONFIRMATION');
  });

  it('the risk console engages only tenant-side scopes and respects explicit-clear', () => {
    expect([...RISK_CONSOLE_ENGAGE_SCOPES].sort()).toEqual(['ACCOUNT', 'STRATEGY', 'SYMBOL']);
    expect(RISK_CONSOLE_ENGAGE_SCOPES).not.toContain('GLOBAL');
    const protection = sources.get('risk-protection.service.ts') ?? '';
    expect(protection).toMatch(/requiresExplicitClear[\s\S]*?acknowledge[\s\S]*?first/iu);
    expect(protection).toMatch(/GLOBAL and EXCHANGE switches are operated from the execution/u);
  });

  it('every mutating route demands a permission and an audit action exists', () => {
    const controller = sources.get('risk.controller.ts') ?? '';
    const postBlocks = controller.split('@Post(').slice(1);
    expect(postBlocks.length).toBeGreaterThanOrEqual(4); // limits, rollback, engage, ack, clear
    for (const block of postBlocks) {
      expect(block).toMatch(/@RequirePermissions\(Permission\.RISK_[A-Z_]+\)/u);
    }
    const policy = sources.get('risk-policy.service.ts') ?? '';
    expect(policy).toContain('AuditAction.RISK_CONFIG_UPDATED');
    expect(policy).toContain('AuditAction.RISK_CONFIG_ROLLED_BACK');
  });
});

describe('Part 8 - DTO discipline', () => {
  const validEntry = () => ({
    ruleId: 'MAX_ORDER_NOTIONAL',
    scope: 'GLOBAL',
    enabled: true,
    value: '1000',
    unit: 'QUOTE_NOTIONAL',
    priority: 0,
    effectiveFromMicros: 0,
    entryVersion: 1,
  });

  const okDocument = () => ({
    entries: [validEntry()],
    changeReason: 'tightening the order ceiling after the sizing review',
  });

  it('accepts a well-formed complete document', async () => {
    const dto = plainToInstance(UpdateRiskPolicyDto, okDocument());
    expect(await validate(dto)).toEqual([]);
  });

  it('rejects scientific-notation values and unknown rules outright', async () => {
    const dto = plainToInstance(UpdateRiskPolicyDto, {
      entries: [
        { ...validEntry(), value: '1e3' },
        { ...validEntry(), ruleId: 'MAX_VIBES' },
      ],
      changeReason: 'should not matter; the entries are already illegal',
    });
    const failures = await validate(dto);
    expect(failures.length).toBeGreaterThan(0);
  });

  it('pins rate windows to the two admitted values', async () => {
    const bad = plainToInstance(UpdateRiskPolicyDto, {
      entries: [{ ...validEntry(), ruleId: 'MAX_ORDER_RATE', unit: 'COUNT', windowMicros: 500 }],
      changeReason: 'five hundred microseconds is not a supported window',
    });
    expect((await validate(bad)).length).toBeGreaterThan(0);

    const ok = plainToInstance(UpdateRiskPolicyDto, {
      entries: [{ ...validEntry(), ruleId: 'MAX_ORDER_RATE', unit: 'COUNT', windowMicros: 60_000_000 }],
      changeReason: 'a documented ceiling of 1000 per minute for burst review',
    });
    expect(await validate(ok)).toEqual([]);
  });

  it('the engage DTO offers no GLOBAL and no EXCHANGE scope', async () => {
    const dto = new EngageRiskSwitchDto();
    Object.assign(dto, { scope: 'GLOBAL', target: null, reason: 'x'.repeat(12) });
    expect((await validate(dto)).length).toBeGreaterThan(0);

    const account = new EngageRiskSwitchDto();
    Object.assign(account, {
      scope: 'ACCOUNT',
      target: '2f8a5d3e-7e0e-4c1a-9b43-6b0d8e0a1c2d',
      reason: 'halting the account pending a sizing investigation',
    });
    expect(await validate(account)).toEqual([]);
  });

  it('clear demands the exact phrase; ack demands a substantial reason', async () => {
    const bad = new ClearRiskSwitchDto();
    Object.assign(bad, { confirm: 'CLEAR PROTECTION', reason: 'y'.repeat(40) });
    expect((await validate(bad)).length).toBeGreaterThan(0);

    const short = new ClearRiskSwitchDto();
    Object.assign(short, { confirm: PROTECTION_CLEAR_CONFIRMATION, reason: 'fine now' });
    expect((await validate(short)).length).toBeGreaterThan(0);

    const good = new ClearRiskSwitchDto();
    Object.assign(good, {
      confirm: PROTECTION_CLEAR_CONFIRMATION,
      reason: 'reviewed the loss window; the sizing bug is fixed and deployed',
    });
    expect(await validate(good)).toEqual([]);
  });

  it('rollback carries the widening phrase, never the clear phrase', async () => {
    const wrong = new RollbackRiskPolicyDto();
    Object.assign(wrong, {
      toVersion: 3,
      changeReason: 'restoring the pre-incident ceiling after the review',
      confirm: PROTECTION_CLEAR_CONFIRMATION,
    });
    expect((await validate(wrong)).length).toBeGreaterThan(0);

    const right = new RollbackRiskPolicyDto();
    Object.assign(right, {
      toVersion: 3,
      changeReason: 'restoring the pre-incident ceiling after the review',
      confirm: WIDEN_CONFIRMATION,
    });
    expect(await validate(right)).toEqual([]);
  });
});

describe('Part 8 - RBAC', () => {
  it('the risk permissions exist, and the two power ones are non-wildcard', () => {
    expect(Permission.RISK_READ).toBe('risk:read');
    expect(Permission.RISK_CONFIG_UPDATE).toBe('risk:config:update');
    expect(Permission.RISK_KILL_SWITCH_UPDATE).toBe('risk:kill_switch_update');
    expect(Permission.RISK_PROTECTION_CLEAR).toBe('risk:protection_clear');
    expect([...NON_WILDCARD_PERMISSIONS]).toEqual(
      expect.arrayContaining(['risk:config:update', 'risk:protection_clear']),
    );
    // Deliberate: engaging a switch only STOPS trading, so a wildcarded
    // grant errs safe; it is not on the explicit-grant list.
    expect(NON_WILDCARD_PERMISSIONS.has('risk:kill_switch_update')).toBe(false);
  });

  it('role grants follow the stop-is-safe, loosen-is-not split', () => {
    const rolePermissions = new Map(
      SYSTEM_ROLE_DEFINITIONS.map((role) => [role.key, role.permissions]),
    );
    const admin = rolePermissions.get(SystemRole.TENANT_ADMIN) ?? [];
    expect(admin).toContain(Permission.RISK_PROTECTION_CLEAR);
    expect(admin).toContain(Permission.RISK_CONFIG_UPDATE);

    const trader = rolePermissions.get(SystemRole.TRADER) ?? [];
    expect(trader).toContain(Permission.RISK_READ);
    expect(trader).toContain(Permission.RISK_KILL_SWITCH_UPDATE);
    expect(trader).not.toContain(Permission.RISK_CONFIG_UPDATE);
    expect(trader).not.toContain(Permission.RISK_PROTECTION_CLEAR);

    const support = rolePermissions.get(SystemRole.SUPPORT) ?? [];
    expect(support).toContain(Permission.RISK_READ);
    expect(support).not.toContain(Permission.RISK_KILL_SWITCH_UPDATE);

    const compliance = rolePermissions.get(SystemRole.COMPLIANCE) ?? [];
    expect(compliance).toContain(Permission.RISK_READ);
    expect(compliance).toContain(Permission.RISK_KILL_SWITCH_UPDATE);
    expect(compliance).not.toContain(Permission.RISK_PROTECTION_CLEAR);

    const follower = rolePermissions.get(SystemRole.FOLLOWER) ?? [];
    expect(follower).not.toContain(Permission.RISK_READ);

    // And the grants actually resolve through the matcher, not just list
    // membership (wildcard/ALL semantics included):
    expect(hasPermission(compliance, 'risk:read')).toBe(true);
    expect(hasPermission(admin, 'risk:protection_clear')).toBe(true);
    expect(hasPermission(follower, 'risk:read')).toBe(false);
  });
});
