import { createHash } from 'node:crypto';

/**
 * Canonical JSON + SHA-256 for risk configuration documents - the TypeScript
 * half of a checksum the Python half recomputes and refuses mismatches on.
 *
 * The rules, stated so this file can be reviewed against them:
 *
 * - the payload shape is EXACTLY `RiskConfiguration.canonical_payload()` in
 *   `wlct_trading/risk/configuration.py`: key names, keys sorted at every
 *   level (`json.dumps(sort_keys=True)`), separators `(",", ":")`;
 * - entry `value` strings are normalised the way Python's
 *   `Decimal.normalize()` + `str()` do it (this is why "5000" canonicalises
 *   to "5E+3" and "0.2500" to "0.25"). The API normalises on the way IN so
 *   the stored document, the API digest and the engine's recomputed digest
 *   read the same string. Python's canonical form is a fixed point of the
 *   same pipeline, which is what makes the round trip safe in both
 *   directions;
 * - correlation-group `maxNotional` is NOT normalised (Python's group model
 *   stores it raw) - the asymmetry is mirrored deliberately here rather
 *   than tidied away, because a tidy mismatch is still a digest failure;
 * - the DTO admits only plain decimals, so the scientific forms this module
 *   can PRODUCE (`dE+n`, `dE-m`) are exactly the two Python emits at the
 *   magnitude boundaries - no parser ambiguity anywhere.
 *
 * Parity against the Python implementation is asserted by
 * `risk-safety.spec.ts` on fixture digests GENERATED by running the Python
 * code (`docs/fixtures/risk_digest_fixtures.json`) - not by a re-reading of
 * this file's intent, which is the kind of agreement a reviewer cannot
 * actually check.
 */

const PLAIN_DECIMAL = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?$/;

/** Normalise a plain decimal string to Python's
 *  `str(Decimal(value).normalize())` output, for every value the DTOs admit. */
export function canonicalDecimalString(value: string): string | null {
  const raw = value.trim();
  if (!PLAIN_DECIMAL.test(raw)) {
    return null;
  }
  const negative = raw.startsWith('-');
  const body = negative ? raw.slice(1) : raw;
  const [intPart, fracPart = ''] = body.split('.');
  let digits = intPart + fracPart;
  const fracLen = fracPart.length;

  // Trailing-zero removal is what normalize() does: each stripped digit
  // raises the exponent by one. The DECIMAL *value* is digits * 10^exponent
  // with exponent = removed - fracLen (positive exponent => scientific
  // notation, exactly Python's str(Decimal.normalize()) rendering rules).
  let removed = 0;
  while (digits.length > 1 && digits.endsWith('0')) {
    digits = digits.slice(0, -1);
    removed += 1;
  }
  if (/^0+$/.test(digits)) {
    return '0';
  }
  // Leading zeros of a fractional decimal (0.0000004 -> digits 00000004)
  // are not significant; strip them before sizing the mantissa. The
  // exponent is unchanged: 00000004 * 10^-7 === 4 * 10^-7.
  const firstSignificant = digits.search(/[1-9]/u);
  if (firstSignificant > 0) {
    digits = digits.slice(firstSignificant);
  }
  const exponent = removed - fracLen;
  const adjusted = digits.length - 1 + exponent;

  if (exponent > 0 || adjusted < -6) {
    // Scientific form: one leading digit, remaining digits after a point
    // only if any remain, E+/-<adjusted>. "5000" -> "5E+3",
    // "250.000" -> "2.5E+2", "0.0000004" -> "4E-7".
    const mantissa =
      digits.length > 1 ? `${digits[0]}.${digits.slice(1)}` : digits;
    const sign = adjusted >= 0 ? `E+${adjusted}` : `E-${-adjusted}`;
    return negative ? `-${mantissa}${sign}` : `${mantissa}${sign}`;
  }
  if (exponent === 0) {
    return negative ? `-${digits}` : digits;
  }
  const shift = -exponent;
  if (shift >= digits.length) {
    const zeros = '0'.repeat(shift - digits.length);
    return negative ? `-0.${zeros}${digits}` : `0.${zeros}${digits}`;
  }
  const intSide = digits.slice(0, digits.length - shift) || '0';
  const fracSide = digits.slice(digits.length - shift);
  return negative ? `-${intSide}.${fracSide}` : `${intSide}.${fracSide}`;
}

/** True when `value` is already in canonical form (used to reject a client
 *  that sends "5000.00" where the stored document must carry "5000"). */
export function isCanonicalDecimalString(value: string): boolean {
  const canonical = canonicalDecimalString(value);
  return canonical !== null && canonical === value.trim();
}

const COMPARE_SCALE = 24;

/** Exact comparison of decimal strings (plain or the canonical scientific
 *  forms) via scaled BigInts. No float appears anywhere in a limit
 *  comparison, in either language. */
export function compareDecimalStrings(a: string, b: string): number {
  const scaled = (value: string): bigint => {
    const match = /^(-?)(\d+)(?:\.(\d+))?(?:E([+-]\d+))?$/.exec(value.trim());
    if (!match) {
      throw new Error(`not a decimal string: ${value}`);
    }
    const negative = match[1] === '-';
    const whole = match[2];
    const frac = match[3] ?? '';
    const exponent = match[4] === undefined ? 0 : Number.parseInt(match[4], 10);
    const digits = whole + frac;
    // value = digits * 10^(exponent - frac.length); scale up by 10^COMPARE_SCALE
    const power = exponent - frac.length + COMPARE_SCALE;
    let magnitude: bigint;
    if (digits === '' || /^0*$/.test(digits)) {
      magnitude = 0n;
    } else {
      const base = BigInt(digits);
      magnitude =
        power >= 0 ? base * 10n ** BigInt(power) : base / 10n ** BigInt(-power);
    }
    return negative ? -magnitude : magnitude;
  };
  const left = scaled(a);
  const right = scaled(b);
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Deterministic minimum over decimal strings; null for the empty input. */
export function minDecimalString(values: readonly string[]): string | null {
  let best: string | null = null;
  for (const value of values) {
    if (best === null || compareDecimalStrings(value, best) < 0) {
      best = value;
    }
  }
  return best;
}

/** `json.dumps(sort_keys=True, separators=(",", ":"))` for the subset of
 *  JSON this module encodes: objects, arrays, strings, integers, booleans,
 *  null. Non-integer numbers THROW - the platform has no decimal that is
 *  legitimately a JSON number, and a silent float here would be the very
 *  bug class this whole boundary exists to refuse. */
export function canonicalJson(payload: unknown): string {
  const encode = (value: unknown): string => {
    if (value === null || value === undefined) {
      return 'null';
    }
    if (typeof value === 'boolean') {
      return value ? 'true' : 'false';
    }
    if (typeof value === 'number') {
      if (!Number.isInteger(value)) {
        throw new Error('canonical JSON rejects non-integer numbers');
      }
      return String(value);
    }
    if (typeof value === 'string') {
      return escapeString(value);
    }
    if (Array.isArray(value)) {
      return `[${value.map(encode).join(',')}]`;
    }
    if (typeof value === 'object') {
      const entries = Object.entries(value as Record<string, unknown>)
        .filter(([, inner]) => inner !== undefined)
        .sort(([first], [second]) => (first < second ? -1 : first > second ? 1 : 0));
      return `{${entries
        .map(([key, inner]) => `${escapeString(key)}:${encode(inner)}`)
        .join(',')}}`;
    }
    throw new Error(`canonical JSON cannot encode ${typeof value}`);
  };
  return encode(payload);
}

/** JSON.stringify plus Python's ensure_ascii escaping for non-ASCII (both
 *  produce lower-case \\uXXXX; validated inputs are ASCII, and a non-ASCII
 *  string reaching here is data hygiene failure, so it round-trips rather
 *  than throws - digests must not depend on transport encodings). */
function escapeString(value: string): string {
  const base = JSON.stringify(value);
  return base.replace(/[\u007f-\uffff]/gu, (character) =>
    `\\u${character.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );
}

export function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}
