/**
 * Canonical machine-readable error codes. Clients switch on these values, never
 * on human readable messages (which are localised and may change).
 */
export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CONFLICT = 'CONFLICT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

  // Authentication
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  ACCOUNT_PENDING_VERIFICATION = 'ACCOUNT_PENDING_VERIFICATION',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  PASSWORD_POLICY_VIOLATION = 'PASSWORD_POLICY_VIOLATION',

  // Two factor
  TWO_FACTOR_REQUIRED = 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID',
  TWO_FACTOR_ALREADY_ENABLED = 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_NOT_ENABLED = 'TWO_FACTOR_NOT_ENABLED',

  // Authorization
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_LIMIT_REACHED = 'SUBSCRIPTION_LIMIT_REACHED',

  // Exchange / trading domain (used from Part 2 onwards)
  EXCHANGE_NOT_SUPPORTED = 'EXCHANGE_NOT_SUPPORTED',
  EXCHANGE_CREDENTIALS_INVALID = 'EXCHANGE_CREDENTIALS_INVALID',
  EXCHANGE_PERMISSION_DENIED = 'EXCHANGE_PERMISSION_DENIED',
  EXCHANGE_RATE_LIMITED = 'EXCHANGE_RATE_LIMITED',
  EXCHANGE_UNAVAILABLE = 'EXCHANGE_UNAVAILABLE',
  EXECUTION_DISABLED = 'EXECUTION_DISABLED',
  RISK_LIMIT_BREACHED = 'RISK_LIMIT_BREACHED',

  // Compliance
  KYC_REQUIRED = 'KYC_REQUIRED',
  KYC_PENDING = 'KYC_PENDING',
  KYC_REJECTED = 'KYC_REJECTED',
}

/** Default HTTP status mapping used by the API exception factory. */
export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = Object.freeze({
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.PAYLOAD_TOO_LARGE]: 413,
  [ErrorCode.UNSUPPORTED_MEDIA_TYPE]: 415,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.TOKEN_REVOKED]: 401,
  [ErrorCode.REFRESH_TOKEN_REUSE_DETECTED]: 401,
  [ErrorCode.ACCOUNT_LOCKED]: 423,
  [ErrorCode.ACCOUNT_DISABLED]: 403,
  [ErrorCode.ACCOUNT_PENDING_VERIFICATION]: 403,
  [ErrorCode.EMAIL_ALREADY_REGISTERED]: 409,
  [ErrorCode.PASSWORD_POLICY_VIOLATION]: 422,
  [ErrorCode.TWO_FACTOR_REQUIRED]: 401,
  [ErrorCode.TWO_FACTOR_INVALID]: 401,
  [ErrorCode.TWO_FACTOR_ALREADY_ENABLED]: 409,
  [ErrorCode.TWO_FACTOR_NOT_ENABLED]: 409,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.TENANT_MISMATCH]: 403,
  [ErrorCode.TENANT_NOT_FOUND]: 404,
  [ErrorCode.TENANT_SUSPENDED]: 403,
  [ErrorCode.FEATURE_DISABLED]: 403,
  [ErrorCode.SUBSCRIPTION_REQUIRED]: 402,
  [ErrorCode.SUBSCRIPTION_LIMIT_REACHED]: 402,
  [ErrorCode.EXCHANGE_NOT_SUPPORTED]: 400,
  [ErrorCode.EXCHANGE_CREDENTIALS_INVALID]: 400,
  [ErrorCode.EXCHANGE_PERMISSION_DENIED]: 403,
  [ErrorCode.EXCHANGE_RATE_LIMITED]: 429,
  [ErrorCode.EXCHANGE_UNAVAILABLE]: 503,
  [ErrorCode.EXECUTION_DISABLED]: 503,
  [ErrorCode.RISK_LIMIT_BREACHED]: 422,
  [ErrorCode.KYC_REQUIRED]: 403,
  [ErrorCode.KYC_PENDING]: 403,
  [ErrorCode.KYC_REJECTED]: 403,
});
