-- Part 11 (disable: the exact inverse of enable.sql). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260913120000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- Policies and the GUC function remain defined (inert while RLS is off), so
-- this file is one-way reversible by re-running enable.sql once the
-- checklist passes again.
ALTER TABLE "account_balance_snapshots" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "account_balance_snapshots" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "notifications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "orders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "positions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "positions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "strategies" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategies" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "users" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" DISABLE ROW LEVEL SECURITY;
