-- Part 11 (enable: the DBA step). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260913120000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- PRE-FLIGHT CHECKLIST - all of it, or do not run this file:
--
--  1. Every API write/read path for a covered table runs inside
--     PrismaService.withTenantRls(tenantId, ...) (which issues
--     set_config('app.tenant_id', $1, true) as the transaction's first
--     statement). Grep the module for direct prisma.<model> usage outside
--     the scoped client as part of the review.
--  2. The application role has neither BYPASSRLS nor superuser:
--        SELECT rolname, rolbypassrls, rolsuper
--        FROM pg_roles WHERE rolname = current_user;
--     FORCE below covers the table OWNER; it does not cover those two
--     privileges, and a role that has them makes the whole exercise
--     theatre. Deployment roles get exactly what they need, nothing more.
--  3. Queue-side writers (audit, alerts, incidents - the excluded nullable
--     tables) are confirmed unaffected: they are not covered here.
--  4. Rollback rehearsed: prisma/rls/disable.sql returns to today's state
--     exactly (NO FORCE, DISABLE, then the migration's objects stay
--     defined and inert).
--  5. Run at low traffic. Enabling is a catalog flip per table; in-flight
--     transactions without the GUC start seeing zero rows immediately -
--     which is the point, and the reason it is a scheduled operation.

-- --- covered tables (43) -------------------------------------------
ALTER TABLE "account_balance_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_balance_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "positions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "positions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategies" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" FORCE ROW LEVEL SECURITY;

-- --- post-enable verification (manual, expect each count to match the
-- --- seeded tenant's own rows under that tenant's GUC, and zero without) --
-- BEGIN; SELECT set_config('app.tenant_id', '<tenant-uuid>', true);
--   SELECT count(*) FROM "account_balance_snapshots";
--   SELECT count(*) FROM "backtest_metrics";
--   SELECT count(*) FROM "backtest_runs";
-- ROLLBACK;
-- Without the GUC, every covered table must read 0 rows as the app role.

-- Excluded (platform-scoped, nullable tenantId) - intentionally untouched:
--   audit_logs (AuditLog)
--   kill_switches (KillSwitch)
--   ops_alerts (OpsAlert)
--   ops_incidents (OpsIncident)
--   roles (Role)
--   security_events (SecurityEvent)
--   subscription_plans (SubscriptionPlan)
