-- Part 11 (grant: the catalog read the enablement audit needs). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260913120000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- WHY THIS FILE EXISTS. The enablement audit asks the database who is connected and whether that
-- role can walk past row-level security:
--
--     SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user;
--
-- When that query returns nothing the audit refuses (ProbeRoleUnknown -> 503
-- ENABLEMENT_ROLE_UNKNOWN in services/execution-engine/app/routers/enablement.py) instead of
-- reading "no row" as "no bypass". `pg_roles` is readable by PUBLIC in a vanilla cluster, so the
-- clusters that trip this are the ones that hardened their catalog by revoking PUBLIC read -
-- which is precisely where the grant below is owed rather than noise.
--
-- WHAT IT GRANTS, in full: SELECT on one catalog view. Not BYPASSRLS, not superuser, not SELECT on
-- any tenant table. A role that has to find out whether it holds a privilege is not thereby given
-- the privilege, and enable.sql's pre-flight refuses a role that holds either - so granting either
-- here would make this file the thing it exists to detect.

-- The grantee is whatever your DATABASE_URL names. `wlct_app` is the role this repository's own
-- .env.example DSN uses, and nothing in this tree decides a deployment's role name for it; change
-- the one line below on a cluster that calls the role something else. Run the file through psql,
-- since \set is a psql meta-command and not SQL.
\set approle wlct_app

GRANT SELECT ON pg_catalog.pg_roles TO :"approle";

-- --- post-grant verification, as the app role, in one transaction ------------------------------
-- BEGIN;
-- SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user;
-- ROLLBACK;
-- One row with both flags false is the state the audit grades. Zero rows keeps the 503, and a row
-- with either flag true is caught by enable.sql's checklist before a policy is enabled - the
-- ordering is deliberate, because a bypass discovered after enablement is an outage report and a
-- bypass discovered before it is a declined deployment.

-- --- inverse -----------------------------------------------------------------------------------
-- REVOKE SELECT ON pg_catalog.pg_roles FROM :"approle";
-- Only to undo this file. A cluster that revoked PUBLIC read on the catalog views does not need
-- this revoke to return to its own baseline, and running it there would leave the audit unable to
-- read the flag it is supposed to grade - the 503 is the safer outcome of the two.
