export const routes = {
  public: {
    landing: '/',
    login: '/login',
    pricing: '/pricing',
    terms: '/terms',
    privacy: '/privacy',
    status: '/status',
  },
  protected: {
    onboarding: '/onboarding',
    dashboard: '/dashboard',
    portfolio: '/portfolio',
    holdings: '/portfolio/holdings',
    performance: '/portfolio/performance',
    attribution: '/portfolio/attribution',
    traders: '/traders',
    traderDetail: (id: string) => `/traders/${id}`,
    strategies: '/strategies',
    strategyDetail: (id: string) => `/strategies/${id}`,
    copyTrading: '/copy-trading',
    exchanges: '/exchanges',
    connectExchange: '/exchanges/connect',
    funding: '/funding',
    deposit: '/funding/deposit',
    withdraw: '/funding/withdraw',
    fundingHistory: '/funding/history',
    billing: '/billing',
    plans: '/billing/plans',
    checkout: '/billing/checkout',
    invoices: '/billing/invoices',
    usage: '/billing/usage',
    statements: '/statements',
    statementDetail: (id: string) => `/statements/${id}`,
    security: '/security',
    mfa: '/security/mfa',
    sessions: '/security/sessions',
    devices: '/security/devices',
    apiKeys: '/security/api-keys',
    account: '/account',
    profile: '/account/profile',
    relationships: '/account/relationships',
    restrictions: '/account/restrictions',
    notifications: '/notifications',
    notificationPrefs: '/notifications/preferences',
  },
} as const;

export const publicRoutes = Object.values(routes.public);
export const protectedRoutes = Object.values(routes.protected).flatMap((v) => typeof v === 'string' ? [v] : []);
