import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { EnvValidationError, validateEnv } from '@wlct/config';

import {
  NON_WILDCARD_PERMISSIONS,
  Permission,
  SYSTEM_ROLE_DEFINITIONS,
  SystemRole,
} from '@wlct/shared-types';
import { isSensitiveKey, redact } from '@wlct/utils';
import { validate } from 'class-validator';
import { plainToInstance } from 'class-transformer';

import {
  ALERT_SEVERITIES,
  ALERT_RULE_CATALOG,
  COMPONENT_STATUSES,
  INCIDENT_LINK_KINDS,
  TRADING_GATES,
} from './alert.constants';
import { evaluateTradingReadiness, type GateEvidence } from './readiness-eval';
import { MetricsRegistry, MetricPolicyError, FORBIDDEN_LABEL_NAMES } from '../../infrastructure/metrics/metrics.registry';
import { createMetricsRegistry } from './metrics.registry.provider';
import { parseAlertsDocument, parseHealthDocument, parseReadinessDocument } from './observability.mapper';
import { ForceResolveAlertDto } from './dto/observability.dto';

/**
 * Part 9 safety tests for the operations surface.
 *
 * Four families, in the order their failures would hurt:
 *
 *  1. CROSS-LANGUAGE PARITY against the Python engine. The TS registry,
 *     evaluator, alert catalog and redaction predicate are hand-written
 *     mirrors of `wlct_trading.observability`. Drift is silent and lands on
 *     an operator's screen during an incident, so BOTH the shared fixture
 *     (generated by libs/trading-core/scripts/gen_observability_fixtures.py)
 *     and live parses of the Python sources are asserted here. A constant
 *     edited on one side fails this suite in CI.
 *
 *  2. METRIC CARDINALITY GUARANTEES. No order ids, no request ids, no
 *     tenant/user identifiers, no URL- or credential-shaped values, allow-
 *     listed label names, bounded symbol domains, and a series cap that
 *     refuses NEW series instead of growing forever. These are the rules
 *     that keep the metrics backend alive; they are asserted against the
 *     rendered text and against the source of every metric-registering file.
 *
 *  3. WHAT THE OPERATIONS SURFACE CANNOT DO. No route disables the risk
 *     engine, submits an order, or touches a kill switch; every mutation is
 *     a POST with a DTO, a permission and an audit path; readiness reports
 *     and nothing in the trading path imports the readiness evaluator.
 *
 *  4. THE READINESS TRUTH TABLE. All 512 gate combinations replayed against
 *     the fixture computed by the Python evaluator, plus the unknown- and
 *     stale-evidence tables. "Both panels agree" is only meaningful if some-
 *     thing checks it mechanically at every commit.
 */

const repoRoot = join(__dirname, '..', '..', '..', '..', '..');
const read = (relative: string): string => readFileSync(join(repoRoot, relative), 'utf8');

const fixture = JSON.parse(
  readFileSync(join(repoRoot, 'docs', 'fixtures', 'observability_fixtures.json'), 'utf8'),
) as {
  prometheus: {
    vectors: Array<{
      name: string;
      service: string;
      families: Array<{
        name: string;
        type: 'counter' | 'gauge' | 'histogram';
        help: string;
        labels: string[];
        buckets?: number[];
        record: Array<{ op: string; labels: Record<string, string>; amount?: number; value?: number; micros?: number }>;
      }>;
      text: string;
    }>;
  };
  redaction: {
    cases: Array<
      | { key: string; expected: boolean }
      | { input: unknown; expected?: unknown; forbidden?: string[] }
    >;
  };
  readiness: {
    gates: string[];
    rows: Array<{ satisfied: string; ready: boolean; blocking: string[] }>;
    unknownRows: Array<{ unknown: string; ready: boolean; blocking: string[] }>;
    staleRows: Array<{ stale: string; ready: boolean; blocking: string[] }>;
  };
  catalogs: {
    alert_rules: Array<{ ruleId: string; severity: string; title: string; requiresRecovery: boolean; blocksTrading: boolean }>;
    alert_severities: string[];
    alert_states: string[];
    health_statuses: string[];
    trading_gates: string[];
    forbidden_labels: string[];
    allowed_labels: string[];
  };
};

describe('Part 9 fixture parity - the two languages render the same bytes', () => {
  const buildFromVector = (vector: (typeof fixture.prometheus.vectors)[number]): MetricsRegistry => {
    const registry = new MetricsRegistry(vector.service);
    for (const family of vector.families) {
      if (family.type === 'counter') {
        registry.registerCounter(family.name, family.help, family.labels);
      } else if (family.type === 'gauge') {
        registry.registerGauge(family.name, family.help, family.labels);
      } else {
        registry.registerHistogram(family.name, family.help, family.labels, {
          buckets: family.buckets ?? [],
        });
      }
      for (const record of family.record) {
        if (record.op === 'inc') {
          registry.inc(family.name, record.labels, record.amount ?? 1);
        } else if (record.op === 'set') {
          registry.setGauge(family.name, record.labels, record.value ?? 0);
        } else {
          registry.observe(family.name, record.labels, record.micros ?? 0);
        }
      }
    }
    return registry;
  };

  it.each(fixture.prometheus.vectors.map((v) => [v.name, v] as const))(
    'rendered exposition matches Python for %s',
    (_name, vector) => {
      const registry = buildFromVector(vector);
      expect(registry.render()).toEqual(vector.text);
    },
  );

  it('redaction predicate agrees with Python on every key case', () => {
    for (const caseEntry of fixture.redaction.cases) {
      if ('key' in caseEntry) {
        expect(isSensitiveKey(caseEntry.key)).toBe(caseEntry.expected);
      }
    }
  });

  it('redact() destroys every forbidden value the Python redactor destroys', () => {
    for (const caseEntry of fixture.redaction.cases) {
      if ('key' in caseEntry) {
        continue;
      }
      const output = redact(caseEntry.input as Record<string, unknown>);
      const rendered = JSON.stringify(output);
      for (const secret of caseEntry.forbidden ?? []) {
        expect(rendered).not.toContain(secret);
      }
      // Where Python declared an exact expectation, TS must match it.
      if ('expected' in caseEntry && caseEntry.expected !== undefined) {
        expect(output).toEqual(caseEntry.expected);
      }
    }
  });
});

describe('Part 9 catalog parity - parsed from live Python source, not re-typed', () => {
  const alertSource = read('libs/trading-core/wlct_trading/observability/alerts.py');

  const parseRuleTuples = (): Array<{ ruleId: string; severity: string; blocks: boolean }> => {
    const entries: Array<{ ruleId: string; severity: string; blocks: boolean }> = [];
    const rulePattern = /AlertRule\(\s*"([A-Z_]+)",\s*AlertSeverity\.(\w+),([\s\S]*?)\),\n/g;
    let match: RegExpExecArray | null = rulePattern.exec(alertSource);
    while (match !== null) {
      const ruleId = match[1];
      const severity = match[2];
      const tail = match[3];
      if (ruleId !== undefined && severity !== undefined) {
        entries.push({ ruleId, severity, blocks: /blocks_trading=True/.test(tail ?? '') });
      }
      match = rulePattern.exec(alertSource);
    }
    return entries;
  };

  it('the rule id sets are identical', () => {
    const python = parseRuleTuples().map((entry) => entry.ruleId).sort();
    const ts = ALERT_RULE_CATALOG.map((entry) => entry.ruleId).sort();
    expect(ts).toEqual(python);
    expect(python.length).toBeGreaterThan(10);
  });

  it('severities and the blocks-trading flag match entry by entry', () => {
    for (const entry of parseRuleTuples()) {
      const mirror = ALERT_RULE_CATALOG.find((candidate) => candidate.ruleId === entry.ruleId);
      expect(mirror).toBeDefined();
      expect(mirror?.severity).toBe(entry.severity);
      expect(mirror?.blocksTrading).toBe(entry.blocks);
    }
  });

  it('every Python rule requires recovery, and the mirror says so too', () => {
    const requires = [...alertSource.matchAll(/requires_recovery=([^,\n]+)/g)].map((m) => m[1]);
    // Default-True means the keyword may be absent; both spellings must
    // resolve to "recovery required", which is the only legal value.
    expect(requires.every((value) => value.trim() === 'True')).toBe(true);
  });

  it('the fixture, the source and the constants agree on the gate list', () => {
    const readinessSource = read('libs/trading-core/wlct_trading/observability/readiness.py');
    const pythonGates = [...readinessSource.matchAll(/TradingGate\(\s*"([a-z_]+)"/g)].map((m) => m[1] as string);
    expect(TRADING_GATES).toEqual(pythonGates);
    expect(fixture.readiness.gates).toEqual(pythonGates);
  });

  it('label policies mirror the Python frozensets exactly', () => {
    const labelsSource = read('libs/trading-core/wlct_trading/observability/labels.py');
    const extractSet = (marker: string): string[] => {
      const block = labelsSource.slice(labelsSource.indexOf(marker));
      const body = block.slice(block.indexOf('{') + 1, block.indexOf('}\n)'));
      return [...body.matchAll(/"([a-z_]+)"/g)].map((m) => m[1] as string).sort();
    };
    const pythonForbidden = extractSet('FORBIDDEN_LABEL_NAMES: frozenset[str] = frozenset(');
    const pythonAllowed = extractSet('ALLOWED_LABEL_NAMES: frozenset[str] = frozenset(');
    expect([...FORBIDDEN_LABEL_NAMES].sort()).toEqual(pythonForbidden);
    const registry = new MetricsRegistry('probe');
    expect(() => registry.registerCounter('wlct_any', 'help', ['shoe_size'])).toThrow(MetricPolicyError);
    expect(pythonAllowed.length).toBeGreaterThan(10);
    // The TS allow-list lives in the fixture; compare against it.
    expect([...fixture.catalogs.allowed_labels].sort()).toEqual(pythonAllowed);
    expect([...fixture.catalogs.forbidden_labels].sort()).toEqual(pythonForbidden);
    void registry;
  });

  it('enum wire strings match on both sides', () => {
    expect(fixture.catalogs.alert_severities).toEqual([...ALERT_SEVERITIES]);
    expect(fixture.catalogs.health_statuses).toEqual([...COMPONENT_STATUSES]);
    const incidentsSource = read('libs/trading-core/wlct_trading/observability/incidents.py');
    const linkSection = incidentsSource.slice(
      incidentsSource.indexOf('class IncidentLinkKind'),
      incidentsSource.indexOf('class IncidentStatus'),
    );
    const pythonLinkKinds = [...linkSection.matchAll(/^\s{4}([A-Z_]+) = "/gm)].map((m) => m[1] as string);
    expect(pythonLinkKinds).toEqual([...INCIDENT_LINK_KINDS]);
  });
});

describe('Part 9 readiness truth table - 530 verdicts replayed', () => {
  const rows: Array<{ satisfied: string; ready: boolean; blocking: string[] }> = fixture.readiness.rows;

  it('the fixture table is complete (2^9 rows)', () => {
    expect(rows.length).toBe(512);
  });

  it('every satisfied-bitmap row matches the TS evaluator', () => {
    for (const row of rows) {
      const evidence: Partial<Record<(typeof TRADING_GATES)[number], GateEvidence>> = {};
      row.satisfied.split('').forEach((bit, index) => {
        const gate = fixture.readiness.gates[index];
        if (gate !== undefined) {
          evidence[gate as (typeof TRADING_GATES)[number]] = { value: bit === '1' };
        }
      });
      const verdict = evaluateTradingReadiness(evidence);
      expect([verdict.tradingReady, verdict.blockingGates]).toEqual([row.ready, row.blocking]);
    }
  });

  it('unknown evidence blocks exactly its own gate', () => {
    for (const row of fixture.readiness.unknownRows) {
      const evidence: Partial<Record<(typeof TRADING_GATES)[number], GateEvidence>> = {};
      for (const gate of fixture.readiness.gates) {
        evidence[gate as (typeof TRADING_GATES)[number]] = {
          value: gate === row.unknown ? null : true,
        };
      }
      const verdict = evaluateTradingReadiness(evidence);
      expect([verdict.tradingReady, verdict.blockingGates]).toEqual([row.ready, row.blocking]);
    }
  });

  it('stale evidence blocks exactly its own gate', () => {
    for (const row of fixture.readiness.staleRows) {
      const evidence: Partial<Record<(typeof TRADING_GATES)[number], GateEvidence>> = {};
      for (const gate of fixture.readiness.gates) {
        evidence[gate as (typeof TRADING_GATES)[number]] =
          gate === row.stale
            ? { value: true, ageMicros: 9_000_000, freshnessBudgetMicros: 2_000_000 }
            : { value: true };
      }
      const verdict = evaluateTradingReadiness(evidence);
      expect([verdict.tradingReady, verdict.blockingGates]).toEqual([row.ready, row.blocking]);
    }
  });

  it('an undeclared gate name is a hard error, not a silent extra key', () => {
    expect(() => evaluateTradingReadiness({ vibes: { value: true } } as never)).toThrow(/undeclared gate/);
  });
});

describe('Part 9 metric cardinality - the rules the registry enforces at the door', () => {
  it('registers allow-listed labels and refuses forbidden or unknown ones', () => {
    const registry = new MetricsRegistry('api');
    expect(() =>
      registry.registerCounter('wlct_orders_submitted_total', 'help', ['exchange', 'result']),
    ).not.toThrow();
    for (const forbidden of ['order_id', 'request_id', 'correlation_id', 'tenant_id', 'api_key', 'token']) {
      expect(() => registry.registerCounter(`wlct_probe_${forbidden}_total`, 'help', [forbidden])).toThrow(
        /forbidden label name/,
      );
    }
    expect(() => registry.registerCounter('wlct_probe_total', 'help', ['shoe_size'])).toThrow(/allow-list/);
    expect(() => registry.registerCounter('wlct_probe_total', 'help', ['result', 'result'])).toThrow(/twice/);
  });

  it('refuses (counts, does not throw) malformed label sets at record time', () => {
    const registry = new MetricsRegistry('api');
    registry.registerCounter('wlct_probe_total', 'help', ['result']);
    expect(() => registry.inc('wlct_probe_total', { result: 'ok', extra: 'x' })).not.toThrow();
    expect(() => registry.inc('wlct_probe_total', { result: 'two words' })).not.toThrow();
    expect(() => registry.inc('wlct_probe_total', { result: '' })).not.toThrow();
    expect(registry.render()).not.toContain('wlct_probe_total'); // every attempt refused
    // ...and the accepted shape renders normally: the refusals above are not a broken registry.
    registry.inc('wlct_probe_total', { result: 'ok' });
    expect(registry.render()).toContain('wlct_probe_total{result="ok",service="api"} 1');
  });

  it('bounded domains reject out-of-set values', () => {
    const registry = new MetricsRegistry('api');
    registry.registerGauge('wlct_probe_age', 'help', ['queue'], {
      bounds: { queue: new Set(['trade-execution', 'risk-control']) },
    });
    registry.setGauge('wlct_probe_age', { queue: 'trade-execution' }, 1);
    registry.setGauge('wlct_probe_age', { queue: 'someone-made-this-up' }, 1);
    const text = registry.render();
    expect(text).toContain('queue="trade-execution"');
    expect(text).not.toContain('someone-made-this-up');
  });

  it('the per-family series cap refuses new series and keeps existing ones recording', () => {
    const registry = new MetricsRegistry('capped');
    registry.registerCounter('wlct_capped_total', 'cap', ['result']);
    for (let index = 0; index < MetricsRegistry.MAX_SERIES_PER_FAMILY + 5; index += 1) {
      registry.inc('wlct_capped_total', { result: `r${index}` }, 1);
    }
    const lines = registry
      .render()
      .split('\n')
      .filter((line) => line.startsWith('wlct_capped_total{'));
    expect(lines.length).toBe(MetricsRegistry.MAX_SERIES_PER_FAMILY);
    expect(registry.render()).toContain(`wlct_registry_series_overflow_total{service="capped"}`);
  });

  it('the API registry exposes only allow-listed label universes', () => {
    const registry = createMetricsRegistry();
    const source = read('apps/api/src/modules/observability/metrics.registry.provider.ts');
    const labelArrays = [...source.matchAll(/register(?:Counter|Gauge|Histogram)\([^)]*?'([a-z_,\s']+)'\]/gs)]
      .flatMap((match) => (match[1] ?? '').split(/[\s,']+/))
      .filter((token) => token.length > 1);
    for (const label of labelArrays) {
      if (FORBIDDEN_LABEL_NAMES.has(label)) {
        throw new Error(`metrics.registry.provider registers forbidden label "${label}"`);
      }
    }
    expect(registry.familyNames().length).toBeGreaterThanOrEqual(4);
  });

  it('assertLabelValuesSafe rejects secret- and URL-shaped inputs', () => {
    expect(() => MetricsRegistry.assertLabelValuesSafe({ result: 'ok' })).not.toThrow();
    expect(() => MetricsRegistry.assertLabelValuesSafe({ api_key: 'abc' })).toThrow(/secret field/);
    expect(() =>
      MetricsRegistry.assertLabelValuesSafe({ component: 'https://user:pass@db.internal/app' }),
    ).toThrow(/URL-/);
    expect(() =>
      MetricsRegistry.assertLabelValuesSafe({
        component: 'header.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.abcdefghij_k',
      }),
    ).toThrow(/URL- or credential/);
  });
});

describe('Part 9 published-document parsing - corrupt mirrors degrade, never crash', () => {
  it('rejects unparseable or over-wide alert documents', () => {
    expect(parseAlertsDocument('not json')).toBeNull();
    expect(parseAlertsDocument('{}')).toBeNull();
    expect(parseAlertsDocument('{"active": [{"alertId": "a"}]}')).toBeNull(); // missing fields
    const good = JSON.stringify({
      active: [
        {
          alertId: 'a1',
          ruleId: 'MARKET_DATA_STALE',
          severity: 'CRITICAL',
          state: 'OPEN',
          component: 'market-data',
          scope: null,
          title: 't',
          condition: 'c',
          firstSeenAtMicros: 1,
          lastSeenAtMicros: 2,
          occurrences: 3,
          observedValue: null,
          thresholdValue: null,
          message: null,
          links: {},
          acknowledgedBy: null,
          acknowledgedAtMicros: null,
          resolvedAtMicros: null,
          resolution: null,
        },
      ],
      counts: { CRITICAL: 1 },
    });
    expect(parseAlertsDocument(good)?.active[0]?.occurrences).toBe(3);
    // A publisher inventing a severity outside the shared enum poisons the
    // whole document (fail-closed parse), not the enum on this side.
    expect(parseAlertsDocument(good.replace('"CRITICAL"', '"APOCALYPTIC"'))).toBeNull();
  });

  it('health documents keep their per-component status whitelist', () => {
    expect(parseHealthDocument('{"status":"HEALTHY","checkedAtMicros":1,"components":[]}')).not.toBeNull();
    expect(parseHealthDocument('{"status":"FINE","checkedAtMicros":1,"components":[]}')).toBeNull();
  });

  it('readiness documents only accept declared gates', () => {
    const doc = JSON.stringify({
      component: 'trading-engine',
      gatesSatisfied: false,
      gates: [{ gate: 'market_data', satisfied: false, reason: 'stale' }],
      note: '',
    });
    expect(parseReadinessDocument(doc)?.gates[0]?.satisfied).toBe(false);
    const evil = doc.replace('market_data', 'vibes');
    expect(parseReadinessDocument(evil)).toBeNull();
  });
});

describe('Part 9 source-level guarantees - what this plane can NEVER do', () => {
  const moduleDir = 'apps/api/src/modules/observability';
  const files = [
    'observability.controller.ts',
    'metrics.controller.ts',
    'alerts.service.ts',
    'incidents.service.ts',
    'observability.service.ts',
    'readiness-eval.ts',
    'metrics.registry.provider.ts',
    'http-metrics.interceptor.ts',
  ];

  it('no suppression comments anywhere in the module', () => {
    for (const file of files) {
      const source = read(`${moduleDir}/${file}`);
      expect(source).not.toMatch(/eslint-disable|@ts-ignore|@ts-expect-error/);
    }
  });

  it('the module never touches the order path or the risk mutation surface', () => {
    const banned = [
      'execution.service',
      'order.service',
      'risk-policy.service',
      'risk-protection.service',
      'queue.service\'.*enqueueOrThrow|TRADE_EXECUTION',
      'updateMany.*orders',
      'update.*killSwitch',
    ];
    for (const file of files) {
      const source = read(`${moduleDir}/${file}`);
      for (const pattern of banned) {
        expect(new RegExp(pattern).test(source)).toBe(false);
      }
    }
  });

  it('every mutation route carries a permission and a DTO body', () => {
    const controller = read(`${moduleDir}/observability.controller.ts`);
    const posts = controller.split('@Post(').slice(1);
    expect(posts.length).toBe(3); // acknowledge, force-resolve, incident status
    for (const post of posts) {
      const block = post.slice(0, post.indexOf('async '));
      expect(block).toMatch(/@RequirePermissions\(Permission\.OPERATIONS_ALERTS_UPDATE\)/);
    }
    const metricsController = read(`${moduleDir}/metrics.controller.ts`);
    expect(metricsController).not.toMatch(/@Post|@Put|@Patch|@Delete/);
    expect(metricsController).toMatch(/@Public\(\)/);
  });

  it('no route disables observability or risk at runtime', () => {
    const all = files.map((file) => read(`${moduleDir}/${file}`)).join('\n');
    expect(all).not.toMatch(/RISK_ENGINE_ENABLED\s*=\s*false|failClosed\s*=\s*false|fail.?closed.{0,20}disable/is);
    expect(all).not.toMatch(/UPDATE\s+(risk_|orders|kill_switches)/i);
  });

  it('the operations writers touch ONLY the ops tables', () => {
    const writePattern = /this\.prisma\.(\w+)\.(create|update|deleteMany|upsert|createMany|delete)\(/g;
    const alerts = [...read(`${moduleDir}/alerts.service.ts`).matchAll(writePattern)].map((m) => m[1] as string);
    expect([...new Set(alerts)].sort()).toEqual(['opsAlert']);
    const incidentsSource = read(`${moduleDir}/incidents.service.ts`);
    const incidents = [...incidentsSource.matchAll(writePattern)].map((m) => m[1] as string);
    expect([...new Set(incidents)].sort()).toEqual(['opsIncident', 'opsIncidentLink']);
  });

  it('the operations alert permission is non-wildcard; reading is not', () => {
    expect(NON_WILDCARD_PERMISSIONS.has(Permission.OPERATIONS_ALERTS_UPDATE)).toBe(true);
    expect(NON_WILDCARD_PERMISSIONS.has(Permission.OPERATIONS_READ)).toBe(false);
  });

  it('role grants match the Part 9 policy', () => {
    const byRole = new Map(SYSTEM_ROLE_DEFINITIONS.map((role) => [role.key, role.permissions]));
    expect(byRole.get(SystemRole.TENANT_ADMIN)).toContain(Permission.OPERATIONS_READ);
    expect(byRole.get(SystemRole.TENANT_ADMIN)).toContain(Permission.OPERATIONS_ALERTS_UPDATE);
    expect(byRole.get(SystemRole.SUPPORT)).toContain(Permission.OPERATIONS_READ);
    expect(byRole.get(SystemRole.SUPPORT)).not.toContain(Permission.OPERATIONS_ALERTS_UPDATE);
    expect(byRole.get(SystemRole.COMPLIANCE)).toContain(Permission.OPERATIONS_READ);
    expect(byRole.get(SystemRole.COMPLIANCE)).not.toContain(Permission.OPERATIONS_ALERTS_UPDATE);
  });
});

describe('Part 9 DTO discipline', () => {
  it('force-resolve demands the phrase and a 20-character reason', async () => {
    const missing = plainToInstance(ForceResolveAlertDto, { reason: 'short', confirmPhrase: 'nope' });
    const errors = await validate(missing);
    const byProperty = new Map(errors.map((error) => [error.property, error]));
    expect(byProperty.has('reason')).toBe(true);
    expect(byProperty.get('confirmPhrase')?.constraints?.equals).toBeDefined();
  });

  it('acknowledge accepts a 5-character reason and rejects a 4-character one', async () => {
    const { AcknowledgeAlertDto } = await import('./dto/observability.dto');
    const good = plainToInstance(AcknowledgeAlertDto, { reason: 'on it' });
    expect(await validate(good)).toHaveLength(0);
    const bad = plainToInstance(AcknowledgeAlertDto, { reason: 'ok' });
    expect((await validate(bad)).length).toBeGreaterThan(0);
  });
});

describe('Part 9 environment validation - production cannot fly blind', () => {
  const base = (overrides: Record<string, string | undefined> = {}): Record<string, string> => {
    const merged: Record<string, string> = {
      NODE_ENV: 'production',
      DATABASE_URL: 'postgresql://user:pass@localhost:5432/db?schema=public',
      DIRECT_DATABASE_URL: 'postgresql://user:pass@localhost:5432/db?schema=public',
      REDIS_URL: 'redis://localhost:6379/0',
      JWT_ACCESS_SECRET: 'a'.repeat(48),
      JWT_REFRESH_SECRET: 'b'.repeat(48),
      ENCRYPTION_MASTER_KEY_BASE64: Buffer.alloc(32, 7).toString('base64'),
      BLIND_INDEX_KEY_BASE64: Buffer.alloc(32, 9).toString('base64'),
      INTERNAL_SERVICE_TOKEN: 'c'.repeat(32),
      EXCHANGE_WEBHOOK_SIGNING_SECRET: 'd'.repeat(32),
      METRICS_TOKEN: 'e'.repeat(32),
      SWAGGER_PASSWORD: 's'.repeat(24),
      DATASET_LOCAL_ROOT: '/var/lib/wlct/datasets',
      DATASET_TEMP_ROOT: '/var/lib/wlct/datasets-tmp',
    };
    for (const [key, value] of Object.entries(overrides)) {
      if (value === undefined) {
        delete merged[key];
      } else {
        merged[key] = value;
      }
    }
    return merged;
  };

  it('accepts the mandatory flags when set', () => {
    expect(() => validateEnv(base())).not.toThrow();
  });

  it('refuses production with observability off', () => {
    expect(() => validateEnv(base({ OBSERVABILITY_ENABLED: 'false' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ METRICS_ENABLED: 'false' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ HEALTH_ENABLED: 'false' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ ALERTING_ENABLED: 'false' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ METRICS_TOKEN: undefined }))).toThrow(EnvValidationError);
  });

  it('retention floors are enforced at parse time', () => {
    expect(() => validateEnv(base({ ALERT_RETENTION_DAYS: '1' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ INCIDENT_RETENTION_DAYS: '2' }))).toThrow(EnvValidationError);
    expect(() => validateEnv(base({ ALERT_DEDUP_WINDOW_MS: '100', HEALTH_REFRESH_MS: '5000' }))).toThrow(
      EnvValidationError,
    );
  });
});
