-- Part 14 - retention ledger for the durable execution store.
--
-- What this table is: the append-only RECORD of pruning runs against
-- engine_order_events (the one table retention may delete from). Rows are
-- written by services/execution-engine/app/retention.py in the
-- transaction that follows the batch loop - one row per COMPLETED run,
-- dry runs included, because "we rehearsed a prune on this date and the
-- answer was 41,902 rows" is exactly the sentence an incident review
-- needs and nobody will remember.
--
-- What refuses are NOT: refusals (memory backend, apply-disabled config)
-- happen before any store handle is reachable, so they never reach this
-- table; there is therefore no outcome/status column and the CHECK that a
-- status column would want is deliberately absent - every row here is a
-- fact that happened, not a report of an attempt.
--
-- This ledger is itself never pruned. It grows by one row per scheduled
-- run (a nightly job: 365 rows per tenant-year), and it is the only
-- defense against "what was deleted and when" being unanswerable.
--
-- Ownership law unchanged from Part 13: this migration is the DDL source
-- of truth, kept in lockstep with apps/api/prisma/schema.prisma (the
-- ExecutionRetentionRun model); the RLS policy for it is generated by the
-- Part 11 machinery from that schema, no hand-written GRANT/RLC here.

CREATE TABLE "engine_retention_runs" (
    "seq" BIGSERIAL NOT NULL,
    "tenant_id" UUID NOT NULL,
    "started_at" BIGINT NOT NULL,
    "finished_at" BIGINT NOT NULL,
    "dry_run" BOOLEAN NOT NULL,
    "event_cutoff_us" BIGINT NOT NULL,
    "rows_deleted" BIGINT NOT NULL,
    "batches" INTEGER NOT NULL,
    "exhausted" BOOLEAN NOT NULL DEFAULT false,
    "instance_id" VARCHAR(64) NOT NULL,
    CONSTRAINT "engine_retention_runs_pkey" PRIMARY KEY ("seq")
);

-- "the last five runs for this tenant" is the only read the inspect
-- endpoint has; seq DESC over the tenant prefix is that query's shape.
CREATE INDEX "engine_retention_runs_tenant_id_seq_idx" ON "engine_retention_runs"("tenant_id", "seq");

-- Restrict, same law as the store tables: the pruning record survives
-- every argument about the tenant it describes.
ALTER TABLE "engine_retention_runs" ADD CONSTRAINT "engine_retention_runs_tenant_id_fkey"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
