-- Part 17 - durable incident recording (the services/execution-engine
-- IncidentRecorder port, previously process-memory-only).
--
-- The core has described incident records as "deliberately rare and deliberately
-- durable" since Part 5, while the only implementation the platform shipped was
-- InMemoryIncidentRecorder. On a deployment running Part 13's store that meant
-- the order survived a restart and the explanation of the order did not, which is
-- the one half of a pair that makes the surviving half unreadable. This table
-- closes the gap; the DDL source of truth stays here, in lockstep with
-- apps/api/prisma/schema.prisma (the ExecutionIncident model), exactly as
-- Part 13's three tables do.
--
-- Shape decisions, each of them borrowed from a table that already had to make
-- it: microsecond BIGINT timestamps (the engine clock, never timestamptz),
-- VARCHAR vocabularies validated by the codec rather than Postgres enums, and a
-- tenant FK that RESTRICTs rather than cascades, because execution history is
-- audit evidence and must not vanish as a side effect of a tenant being removed.
--
-- No GRANT/RLC statements here: as with every prior migration, policy creation
-- for this table is generated by the Part 11 machinery into its own artefacts
-- (apps/api/prisma/rls/enable.sql, disable.sql, rls_coverage.json), so the
-- tenant-scoped set is derived from the schema rather than remembered by hand.

CREATE TABLE "engine_incidents" (
    -- The core's uuid, not a serial: the same identifier is what the log line,
    -- the alert and this row all point at. A per-tenant sequence would make
    -- "which incident did the page refer to?" unanswerable across tenants.
    "incident_id" VARCHAR(64) NOT NULL,
    "tenant_id" UUID NOT NULL,

    -- Nullable because most incidents have no account (a credential refusal, a
    -- lock outage, a store that could not be written). A blank string here would
    -- turn "no account" into an account named empty-string, which is a value a
    -- filter matches and a dashboard groups.
    "account_id" VARCHAR(64),

    "incident_type" VARCHAR(48) NOT NULL,
    "severity" VARCHAR(16) NOT NULL,
    "summary" VARCHAR(500) NOT NULL,

    "exchange" VARCHAR(32),
    "symbol" VARCHAR(32),

    -- Plain columns, deliberately NOT a composite FK to engine_orders. An incident
    -- often has no order at all, and a MATCH SIMPLE composite key with a nullable
    -- column is a constraint that never fires while reading like a guarantee -
    -- worse than no constraint, because it invites the next reader to assume the
    -- pairing was checked.
    "order_id" VARCHAR(64),
    "client_order_id" VARCHAR(128),

    -- The normalised taxonomy from the core (ExecutionErrorCode), stored as the
    -- string it already is on the wire.
    "error_code" VARCHAR(48),

    -- Already scrubbed by ExecutionIncident.create. Stored as JSONB text-shaped
    -- values and never re-derived: the details are the evidence, and an evidence
    -- column that a later write can rewrite is not evidence.
    "details" JSONB NOT NULL DEFAULT '{}'::jsonb,

    "occurred_at" BIGINT NOT NULL,

    -- Insert-only law. `resolve()` in the core returns a NEW incident, so there
    -- is no UPDATE statement anywhere against this table: the two columns below
    -- are written once and read forever. The index on (tenant_id, resolved) is
    -- the physical form of that law - open incidents are the query, and the
    -- closed ones are history that nothing re-touches.
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "resolution_note" VARCHAR(500),

    -- Insertion order, so "newest first" is decidable when two incidents share one
    -- microsecond (one failed command routinely emits a pair).
    "seq" BIGSERIAL NOT NULL,
    CONSTRAINT "engine_incidents_pkey" PRIMARY KEY ("seq")
);

-- The incident identity, enforced where the record is born: the core mints a
-- uuid per incident, and a duplicate on insert means a caller replayed a write
-- (at-least-once delivery), which must be a no-op rather than a second row in an
-- audit trail.
CREATE UNIQUE INDEX "engine_incidents_incident_id_key" ON "engine_incidents"("incident_id");

CREATE INDEX "engine_incidents_tenant_open_idx" ON "engine_incidents"("tenant_id", "resolved", "occurred_at");
CREATE INDEX "engine_incidents_tenant_type_idx" ON "engine_incidents"("tenant_id", "incident_type", "occurred_at");

ALTER TABLE "engine_incidents" ADD CONSTRAINT "engine_incidents_tenant_id_fkey"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
