-- Part 13 - durable execution-engine store (the services/execution-engine
-- OrderStore port, previously process-memory-only).
--
-- Ownership law unchanged: this migration is the DDL source of truth, kept
-- in lockstep with apps/api/prisma/schema.prisma (the ExecutionOrder /
-- ExecutionOrderEvent / ExecutionOrderFill models). The engine service
-- writes these tables over asyncpg; the API and the RLS generator see them
-- through this schema. Deliberate shape decisions are documented at the
-- models - decimal-as-text columns, microsecond BIGINT timestamps,
-- VARCHAR vocabularies validated by the codec rather than Postgres enums,
-- and composite (tenant_id, order_id) FKs so a child row cannot pair one
-- tenant with another tenant's order.
--
-- No GRANT/RLC statements here: same as every prior migration, the role
-- topology is the deployment's business (see docs/PART11_ROW_LEVEL_SECURITY
-- and the generated enable.sql checklist); policy creation for these
-- tables is generated by the Part 11 machinery into its own migration.

CREATE TABLE "engine_orders" (
    "tenant_id" UUID NOT NULL,
    "order_id" VARCHAR(64) NOT NULL,
    "client_order_id" VARCHAR(128) NOT NULL,
    "account_id" VARCHAR(64) NOT NULL,
    "strategy_id" VARCHAR(64),
    "exchange" VARCHAR(32) NOT NULL,
    "symbol" VARCHAR(32) NOT NULL,
    "side" VARCHAR(8) NOT NULL,
    "order_type" VARCHAR(32) NOT NULL,
    "time_in_force" VARCHAR(8) NOT NULL,
    "reduce_only" BOOLEAN NOT NULL DEFAULT false,
    "signal_id" VARCHAR(64),
    "is_simulated" BOOLEAN NOT NULL,
    "status" VARCHAR(24) NOT NULL,
    "exchange_order_id" VARCHAR(64),
    "quantity" VARCHAR(40) NOT NULL,
    "price" VARCHAR(40),
    "stop_price" VARCHAR(40),
    "filled_quantity" VARCHAR(40) NOT NULL,
    "average_fill_price" VARCHAR(64),
    "cumulative_fee" VARCHAR(64) NOT NULL,
    "fee_currency" VARCHAR(16),
    "rejection_reason" VARCHAR(500),
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    "submitted_at" BIGINT,
    "terminal_at" BIGINT,
    "reconciliation_state" VARCHAR(24),
    CONSTRAINT "engine_orders_pkey" PRIMARY KEY ("tenant_id", "order_id")
);

-- The cross-worker idempotency law, database-enforced: one client order id
-- per tenant, reservation races ride this index via ON CONFLICT.
CREATE UNIQUE INDEX "engine_orders_tenant_client_key" ON "engine_orders"("tenant_id", "client_order_id");

-- Open-order lists by account (the reconcile command's shape) and the
-- reconciliation-state scan (a flagged sweep is rare; a NULL-everywhere
-- column makes a full-table index the cheap one to keep).
CREATE INDEX "engine_orders_tenant_id_account_id_status_idx" ON "engine_orders"("tenant_id", "account_id", "status");
CREATE INDEX "engine_orders_reconciliation_state_idx" ON "engine_orders"("reconciliation_state");

-- Restrict, not Cascade: execution history is audit evidence and must not
-- vanish as a side effect of tenant removal.
ALTER TABLE "engine_orders" ADD CONSTRAINT "engine_orders_tenant_id_fkey"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- The append-only event journal. "seq" is the insertion-order identity:
-- list_events answers in it, so history survives a restart in the order it
-- was written rather than in whatever order microsecond timestamps happen
-- to sort (two transitions in one tick share a timestamp routinely).
CREATE TABLE "engine_order_events" (
    "seq" BIGSERIAL NOT NULL,
    "tenant_id" UUID NOT NULL,
    "order_id" VARCHAR(64) NOT NULL,
    "event_id" VARCHAR(64) NOT NULL,
    "previous_status" VARCHAR(24),
    "status" VARCHAR(24) NOT NULL,
    "reason" VARCHAR(500),
    "occurred_at" BIGINT NOT NULL,
    "payload" JSONB NOT NULL,
    CONSTRAINT "engine_order_events_pkey" PRIMARY KEY ("seq")
);

CREATE INDEX "engine_order_events_tenant_id_order_id_seq_idx" ON "engine_order_events"("tenant_id", "order_id", "seq");
CREATE INDEX "engine_order_events_tenant_id_event_id_idx" ON "engine_order_events"("tenant_id", "event_id");

-- Composite reference: the child's tenant must be its order's tenant.
ALTER TABLE "engine_order_events" ADD CONSTRAINT "engine_order_events_tenant_id_order_id_fkey"
    FOREIGN KEY ("tenant_id", "order_id") REFERENCES "engine_orders"("tenant_id", "order_id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "engine_order_fills" (
    "seq" BIGSERIAL NOT NULL,
    "tenant_id" UUID NOT NULL,
    "order_id" VARCHAR(64) NOT NULL,
    "fill_id" VARCHAR(128) NOT NULL,
    "trade_id" VARCHAR(128) NOT NULL,
    "price" VARCHAR(40) NOT NULL,
    "quantity" VARCHAR(40) NOT NULL,
    "fee" VARCHAR(64) NOT NULL,
    "fee_currency" VARCHAR(16) NOT NULL,
    "is_maker" BOOLEAN NOT NULL,
    "is_simulated" BOOLEAN NOT NULL,
    "exchange_timestamp" BIGINT NOT NULL,
    "received_timestamp" BIGINT NOT NULL,
    "symbol" VARCHAR(32),
    "side" VARCHAR(8),
    "exchange" VARCHAR(32),
    "quote_quantity" VARCHAR(64),
    "exchange_order_id" VARCHAR(64),
    CONSTRAINT "engine_order_fills_pkey" PRIMARY KEY ("seq")
);

-- record_fill's idempotency: ON CONFLICT DO NOTHING against this unique
-- index is what turns an at-least-once delivery of the same execution into
-- a False answer instead of a second row the order's aggregate would
-- double-count.
CREATE UNIQUE INDEX "engine_order_fills_tenant_fill_key" ON "engine_order_fills"("tenant_id", "fill_id");

CREATE INDEX "engine_order_fills_tenant_id_order_id_seq_idx" ON "engine_order_fills"("tenant_id", "order_id", "seq");

ALTER TABLE "engine_order_fills" ADD CONSTRAINT "engine_order_fills_tenant_id_order_id_fkey"
    FOREIGN KEY ("tenant_id", "order_id") REFERENCES "engine_orders"("tenant_id", "order_id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
