-- Part 11 (migration: functions + policies (NOT enabling)). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260913120000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- The single source of the request's tenant, read from the transaction-local
-- GUC that PrismaService.withTenantRls() sets via set_config(..., true).
-- STABLE so the planner evaluates it once per query, not per row.
CREATE OR REPLACE FUNCTION wlct_current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

-- AccountBalanceSnapshot
CREATE POLICY tenant_isolation ON "account_balance_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestMetric
CREATE POLICY tenant_isolation ON "backtest_metrics"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestRun
CREATE POLICY tenant_isolation ON "backtest_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestTrade
CREATE POLICY tenant_isolation ON "backtest_trades"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionEngineIncident
CREATE POLICY tenant_isolation ON "engine_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrderEvent
CREATE POLICY tenant_isolation ON "engine_order_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrderFill
CREATE POLICY tenant_isolation ON "engine_order_fills"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrder
CREATE POLICY tenant_isolation ON "engine_orders"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionRetentionRun
CREATE POLICY tenant_isolation ON "engine_retention_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExchangeStreamSession
CREATE POLICY tenant_isolation ON "exchange_stream_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionIncident
CREATE POLICY tenant_isolation ON "execution_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- KycProfile
CREATE POLICY tenant_isolation ON "kyc_profiles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- LoginAttempt
CREATE POLICY tenant_isolation ON "login_attempts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Notification
CREATE POLICY tenant_isolation ON "notifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Order
CREATE POLICY tenant_isolation ON "orders"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PaperPortfolioSnapshot
CREATE POLICY tenant_isolation ON "paper_portfolio_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PaperTradingSession
CREATE POLICY tenant_isolation ON "paper_trading_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Position
CREATE POLICY tenant_isolation ON "positions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ReconciliationDiscrepancy
CREATE POLICY tenant_isolation ON "reconciliation_discrepancies"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ReconciliationRun
CREATE POLICY tenant_isolation ON "reconciliation_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RefreshToken
CREATE POLICY tenant_isolation ON "refresh_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskConfigurationVersion
CREATE POLICY tenant_isolation ON "risk_configuration_versions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskConfiguration
CREATE POLICY tenant_isolation ON "risk_configurations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskEvent
CREATE POLICY tenant_isolation ON "risk_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskProtectionTrip
CREATE POLICY tenant_isolation ON "risk_protection_actions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskSnapshotMetadata
CREATE POLICY tenant_isolation ON "risk_snapshot_metadata"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Strategy
CREATE POLICY tenant_isolation ON "strategies"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyCheckpoint
CREATE POLICY tenant_isolation ON "strategy_checkpoints"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyIncident
CREATE POLICY tenant_isolation ON "strategy_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyRun
CREATE POLICY tenant_isolation ON "strategy_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantApiKey
CREATE POLICY tenant_isolation ON "tenant_api_keys"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantBranding
CREATE POLICY tenant_isolation ON "tenant_branding"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantDomain
CREATE POLICY tenant_isolation ON "tenant_domains"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantFeatureFlag
CREATE POLICY tenant_isolation ON "tenant_feature_flags"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantSetting
CREATE POLICY tenant_isolation ON "tenant_settings"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantSubscription
CREATE POLICY tenant_isolation ON "tenant_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingAccount
CREATE POLICY tenant_isolation ON "trading_accounts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingSession
CREATE POLICY tenant_isolation ON "trading_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingSymbol
CREATE POLICY tenant_isolation ON "trading_symbols"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UserRole
CREATE POLICY tenant_isolation ON "user_roles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UserSession
CREATE POLICY tenant_isolation ON "user_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- User
CREATE POLICY tenant_isolation ON "users"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- VerificationToken
CREATE POLICY tenant_isolation ON "verification_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Deliberately NOT enabled here. `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`
-- (and FORCE) is the prisma/rls/enable.sql DBA step, run only after the
-- pre-flight checklist there passes - enabling before every write path
-- adopts withTenantRls() turns defence into outage, and that trade is made
-- once, on purpose, by a human with the checklist.
--
-- Excluded by design (nullable tenantId; platform-scoped rows):

--   audit_logs                         (AuditLog)
--   kill_switches                      (KillSwitch)
--   ops_alerts                         (OpsAlert)
--   ops_incidents                      (OpsIncident)
--   roles                              (Role)
--   security_events                    (SecurityEvent)
--   subscription_plans                 (SubscriptionPlan)
-- Their tenant-bearing rows remain filtered by the tenant-scoped factory;
-- a strict policy here would hide the NULL-tenant platform rows that are
-- nobody's cross-tenant secret. The exclusion is a decision, listed in
-- rls_coverage.json and pinned by rls-coverage.spec.ts - never an oversight.
